// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: idios/v1/artifacts.proto

package idiosv1

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for Artifact.
// This method handles enum_value fields and nested messages: kind, capture_gap
func (x *Artifact) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite kind to custom enum_value strings
	for _, k := range []string{"kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := artifactKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(artifactKindToJSON[e])
		}
	}

	// Rewrite capture_gap to custom enum_value strings
	for _, k := range []string{"captureGap", "capture_gap"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := captureGapFromJSON[s]; ok {
			raw[k], _ = json.Marshal(captureGapToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for Artifact.
func (x *Artifact) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for Artifact.
// This method handles enum_value fields and nested messages: kind, capture_gap
func (x *Artifact) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite kind from custom enum_value strings to proto names
	for _, k := range []string{"kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := artifactKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite capture_gap from custom enum_value strings to proto names
	for _, k := range []string{"captureGap", "capture_gap"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := captureGapFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for Artifact.
func (x *Artifact) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
