// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: idios/v1/common.proto

package idiosv1

import (
	"encoding/json"
	"fmt"
)

var categoryToJSON = map[Category]string{
	Category_CATEGORY_UNSPECIFIED:   "CATEGORY_UNSPECIFIED",
	Category_CATEGORY_OOM:           "oom",
	Category_CATEGORY_CRASH:         "crash",
	Category_CATEGORY_IMAGE_PULL:    "image_pull",
	Category_CATEGORY_CONFIG:        "config",
	Category_CATEGORY_PROBE:         "probe",
	Category_CATEGORY_SCHEDULING:    "scheduling",
	Category_CATEGORY_NODE_PRESSURE: "node_pressure",
	Category_CATEGORY_RESCHEDULED:   "rescheduled",
	Category_CATEGORY_JOB_FAILED:    "job_failed",
	Category_CATEGORY_OTHER:         "other",
	Category_CATEGORY_STUCK:         "stuck",
	Category_CATEGORY_UNCLEAN_EXIT:  "unclean_exit",
}

var categoryFromJSON = map[string]Category{
	"CATEGORY_UNSPECIFIED":   Category_CATEGORY_UNSPECIFIED,
	"oom":                    Category_CATEGORY_OOM,
	"crash":                  Category_CATEGORY_CRASH,
	"image_pull":             Category_CATEGORY_IMAGE_PULL,
	"config":                 Category_CATEGORY_CONFIG,
	"probe":                  Category_CATEGORY_PROBE,
	"scheduling":             Category_CATEGORY_SCHEDULING,
	"node_pressure":          Category_CATEGORY_NODE_PRESSURE,
	"rescheduled":            Category_CATEGORY_RESCHEDULED,
	"job_failed":             Category_CATEGORY_JOB_FAILED,
	"other":                  Category_CATEGORY_OTHER,
	"stuck":                  Category_CATEGORY_STUCK,
	"unclean_exit":           Category_CATEGORY_UNCLEAN_EXIT,
	"CATEGORY_OOM":           Category_CATEGORY_OOM,
	"CATEGORY_CRASH":         Category_CATEGORY_CRASH,
	"CATEGORY_IMAGE_PULL":    Category_CATEGORY_IMAGE_PULL,
	"CATEGORY_CONFIG":        Category_CATEGORY_CONFIG,
	"CATEGORY_PROBE":         Category_CATEGORY_PROBE,
	"CATEGORY_SCHEDULING":    Category_CATEGORY_SCHEDULING,
	"CATEGORY_NODE_PRESSURE": Category_CATEGORY_NODE_PRESSURE,
	"CATEGORY_RESCHEDULED":   Category_CATEGORY_RESCHEDULED,
	"CATEGORY_JOB_FAILED":    Category_CATEGORY_JOB_FAILED,
	"CATEGORY_OTHER":         Category_CATEGORY_OTHER,
	"CATEGORY_STUCK":         Category_CATEGORY_STUCK,
	"CATEGORY_UNCLEAN_EXIT":  Category_CATEGORY_UNCLEAN_EXIT,
}

func (x Category) MarshalJSON() ([]byte, error) {
	if s, ok := categoryToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *Category) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := categoryFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown Category value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = Category(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into Category", string(data))
}

var closeReasonToJSON = map[CloseReason]string{
	CloseReason_CLOSE_REASON_UNSPECIFIED:  "CLOSE_REASON_UNSPECIFIED",
	CloseReason_CLOSE_REASON_RECOVERED:    "recovered",
	CloseReason_CLOSE_REASON_POD_DELETED:  "pod_deleted",
	CloseReason_CLOSE_REASON_JOB_FINISHED: "job_finished",
	CloseReason_CLOSE_REASON_MANUAL:       "manual",
}

var closeReasonFromJSON = map[string]CloseReason{
	"CLOSE_REASON_UNSPECIFIED":  CloseReason_CLOSE_REASON_UNSPECIFIED,
	"recovered":                 CloseReason_CLOSE_REASON_RECOVERED,
	"pod_deleted":               CloseReason_CLOSE_REASON_POD_DELETED,
	"job_finished":              CloseReason_CLOSE_REASON_JOB_FINISHED,
	"manual":                    CloseReason_CLOSE_REASON_MANUAL,
	"CLOSE_REASON_RECOVERED":    CloseReason_CLOSE_REASON_RECOVERED,
	"CLOSE_REASON_POD_DELETED":  CloseReason_CLOSE_REASON_POD_DELETED,
	"CLOSE_REASON_JOB_FINISHED": CloseReason_CLOSE_REASON_JOB_FINISHED,
	"CLOSE_REASON_MANUAL":       CloseReason_CLOSE_REASON_MANUAL,
}

func (x CloseReason) MarshalJSON() ([]byte, error) {
	if s, ok := closeReasonToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *CloseReason) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := closeReasonFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown CloseReason value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = CloseReason(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into CloseReason", string(data))
}

var incidentStateToJSON = map[IncidentState]string{
	IncidentState_INCIDENT_STATE_UNSPECIFIED:  "INCIDENT_STATE_UNSPECIFIED",
	IncidentState_INCIDENT_STATE_OPEN:         "open",
	IncidentState_INCIDENT_STATE_ACKNOWLEDGED: "acknowledged",
	IncidentState_INCIDENT_STATE_RECOVERED:    "recovered",
	IncidentState_INCIDENT_STATE_POD_DELETED:  "pod_deleted",
	IncidentState_INCIDENT_STATE_JOB_FINISHED: "job_finished",
	IncidentState_INCIDENT_STATE_MANUAL:       "manual",
	IncidentState_INCIDENT_STATE_DISMISSED:    "dismissed",
	IncidentState_INCIDENT_STATE_ATTENTION:    "attention",
}

var incidentStateFromJSON = map[string]IncidentState{
	"INCIDENT_STATE_UNSPECIFIED":  IncidentState_INCIDENT_STATE_UNSPECIFIED,
	"open":                        IncidentState_INCIDENT_STATE_OPEN,
	"acknowledged":                IncidentState_INCIDENT_STATE_ACKNOWLEDGED,
	"recovered":                   IncidentState_INCIDENT_STATE_RECOVERED,
	"pod_deleted":                 IncidentState_INCIDENT_STATE_POD_DELETED,
	"job_finished":                IncidentState_INCIDENT_STATE_JOB_FINISHED,
	"manual":                      IncidentState_INCIDENT_STATE_MANUAL,
	"dismissed":                   IncidentState_INCIDENT_STATE_DISMISSED,
	"attention":                   IncidentState_INCIDENT_STATE_ATTENTION,
	"INCIDENT_STATE_OPEN":         IncidentState_INCIDENT_STATE_OPEN,
	"INCIDENT_STATE_ACKNOWLEDGED": IncidentState_INCIDENT_STATE_ACKNOWLEDGED,
	"INCIDENT_STATE_RECOVERED":    IncidentState_INCIDENT_STATE_RECOVERED,
	"INCIDENT_STATE_POD_DELETED":  IncidentState_INCIDENT_STATE_POD_DELETED,
	"INCIDENT_STATE_JOB_FINISHED": IncidentState_INCIDENT_STATE_JOB_FINISHED,
	"INCIDENT_STATE_MANUAL":       IncidentState_INCIDENT_STATE_MANUAL,
	"INCIDENT_STATE_DISMISSED":    IncidentState_INCIDENT_STATE_DISMISSED,
	"INCIDENT_STATE_ATTENTION":    IncidentState_INCIDENT_STATE_ATTENTION,
}

func (x IncidentState) MarshalJSON() ([]byte, error) {
	if s, ok := incidentStateToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *IncidentState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := incidentStateFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown IncidentState value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = IncidentState(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into IncidentState", string(data))
}

var captureGapToJSON = map[CaptureGap]string{
	CaptureGap_CAPTURE_GAP_UNSPECIFIED:     "CAPTURE_GAP_UNSPECIFIED",
	CaptureGap_CAPTURE_GAP_POD_DELETED:     "pod_deleted",
	CaptureGap_CAPTURE_GAP_NO_PREVIOUS_RUN: "no_previous_run",
	CaptureGap_CAPTURE_GAP_FORBIDDEN:       "forbidden",
	CaptureGap_CAPTURE_GAP_NO_OUTPUT:       "no_output",
	CaptureGap_CAPTURE_GAP_KUBELET_ERROR:   "kubelet_error",
	CaptureGap_CAPTURE_GAP_UNKNOWN:         "unknown",
	CaptureGap_CAPTURE_GAP_UNOBSERVABLE:    "unobservable",
}

var captureGapFromJSON = map[string]CaptureGap{
	"CAPTURE_GAP_UNSPECIFIED":     CaptureGap_CAPTURE_GAP_UNSPECIFIED,
	"pod_deleted":                 CaptureGap_CAPTURE_GAP_POD_DELETED,
	"no_previous_run":             CaptureGap_CAPTURE_GAP_NO_PREVIOUS_RUN,
	"forbidden":                   CaptureGap_CAPTURE_GAP_FORBIDDEN,
	"no_output":                   CaptureGap_CAPTURE_GAP_NO_OUTPUT,
	"kubelet_error":               CaptureGap_CAPTURE_GAP_KUBELET_ERROR,
	"unknown":                     CaptureGap_CAPTURE_GAP_UNKNOWN,
	"unobservable":                CaptureGap_CAPTURE_GAP_UNOBSERVABLE,
	"CAPTURE_GAP_POD_DELETED":     CaptureGap_CAPTURE_GAP_POD_DELETED,
	"CAPTURE_GAP_NO_PREVIOUS_RUN": CaptureGap_CAPTURE_GAP_NO_PREVIOUS_RUN,
	"CAPTURE_GAP_FORBIDDEN":       CaptureGap_CAPTURE_GAP_FORBIDDEN,
	"CAPTURE_GAP_NO_OUTPUT":       CaptureGap_CAPTURE_GAP_NO_OUTPUT,
	"CAPTURE_GAP_KUBELET_ERROR":   CaptureGap_CAPTURE_GAP_KUBELET_ERROR,
	"CAPTURE_GAP_UNKNOWN":         CaptureGap_CAPTURE_GAP_UNKNOWN,
	"CAPTURE_GAP_UNOBSERVABLE":    CaptureGap_CAPTURE_GAP_UNOBSERVABLE,
}

func (x CaptureGap) MarshalJSON() ([]byte, error) {
	if s, ok := captureGapToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *CaptureGap) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := captureGapFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown CaptureGap value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = CaptureGap(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into CaptureGap", string(data))
}

var deletionSourceToJSON = map[DeletionSource]string{
	DeletionSource_DELETION_SOURCE_UNSPECIFIED: "DELETION_SOURCE_UNSPECIFIED",
	DeletionSource_DELETION_SOURCE_WATCH:       "watch",
	DeletionSource_DELETION_SOURCE_RECONCILE:   "reconcile",
	DeletionSource_DELETION_SOURCE_UNWATCHED:   "unwatched",
}

var deletionSourceFromJSON = map[string]DeletionSource{
	"DELETION_SOURCE_UNSPECIFIED": DeletionSource_DELETION_SOURCE_UNSPECIFIED,
	"watch":                       DeletionSource_DELETION_SOURCE_WATCH,
	"reconcile":                   DeletionSource_DELETION_SOURCE_RECONCILE,
	"unwatched":                   DeletionSource_DELETION_SOURCE_UNWATCHED,
	"DELETION_SOURCE_WATCH":       DeletionSource_DELETION_SOURCE_WATCH,
	"DELETION_SOURCE_RECONCILE":   DeletionSource_DELETION_SOURCE_RECONCILE,
	"DELETION_SOURCE_UNWATCHED":   DeletionSource_DELETION_SOURCE_UNWATCHED,
}

func (x DeletionSource) MarshalJSON() ([]byte, error) {
	if s, ok := deletionSourceToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *DeletionSource) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := deletionSourceFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown DeletionSource value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = DeletionSource(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into DeletionSource", string(data))
}

var deletionReasonToJSON = map[DeletionReason]string{
	DeletionReason_DELETION_REASON_UNSPECIFIED: "DELETION_REASON_UNSPECIFIED",
	DeletionReason_DELETION_REASON_ROLLOUT:     "rollout",
	DeletionReason_DELETION_REASON_REPLACED:    "replaced",
	DeletionReason_DELETION_REASON_SCALED_DOWN: "scaled_down",
	DeletionReason_DELETION_REASON_JOB_PRUNED:  "job_pruned",
	DeletionReason_DELETION_REASON_UNKNOWN:     "unknown",
	DeletionReason_DELETION_REASON_EVICTED:     "evicted",
}

var deletionReasonFromJSON = map[string]DeletionReason{
	"DELETION_REASON_UNSPECIFIED": DeletionReason_DELETION_REASON_UNSPECIFIED,
	"rollout":                     DeletionReason_DELETION_REASON_ROLLOUT,
	"replaced":                    DeletionReason_DELETION_REASON_REPLACED,
	"scaled_down":                 DeletionReason_DELETION_REASON_SCALED_DOWN,
	"job_pruned":                  DeletionReason_DELETION_REASON_JOB_PRUNED,
	"unknown":                     DeletionReason_DELETION_REASON_UNKNOWN,
	"evicted":                     DeletionReason_DELETION_REASON_EVICTED,
	"DELETION_REASON_ROLLOUT":     DeletionReason_DELETION_REASON_ROLLOUT,
	"DELETION_REASON_REPLACED":    DeletionReason_DELETION_REASON_REPLACED,
	"DELETION_REASON_SCALED_DOWN": DeletionReason_DELETION_REASON_SCALED_DOWN,
	"DELETION_REASON_JOB_PRUNED":  DeletionReason_DELETION_REASON_JOB_PRUNED,
	"DELETION_REASON_UNKNOWN":     DeletionReason_DELETION_REASON_UNKNOWN,
	"DELETION_REASON_EVICTED":     DeletionReason_DELETION_REASON_EVICTED,
}

func (x DeletionReason) MarshalJSON() ([]byte, error) {
	if s, ok := deletionReasonToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *DeletionReason) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := deletionReasonFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown DeletionReason value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = DeletionReason(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into DeletionReason", string(data))
}

var containerKindToJSON = map[ContainerKind]string{
	ContainerKind_CONTAINER_KIND_UNSPECIFIED: "CONTAINER_KIND_UNSPECIFIED",
	ContainerKind_CONTAINER_KIND_INIT:        "init",
	ContainerKind_CONTAINER_KIND_SIDECAR:     "sidecar",
	ContainerKind_CONTAINER_KIND_APP:         "app",
	ContainerKind_CONTAINER_KIND_EPHEMERAL:   "ephemeral",
}

var containerKindFromJSON = map[string]ContainerKind{
	"CONTAINER_KIND_UNSPECIFIED": ContainerKind_CONTAINER_KIND_UNSPECIFIED,
	"init":                       ContainerKind_CONTAINER_KIND_INIT,
	"sidecar":                    ContainerKind_CONTAINER_KIND_SIDECAR,
	"app":                        ContainerKind_CONTAINER_KIND_APP,
	"ephemeral":                  ContainerKind_CONTAINER_KIND_EPHEMERAL,
	"CONTAINER_KIND_INIT":        ContainerKind_CONTAINER_KIND_INIT,
	"CONTAINER_KIND_SIDECAR":     ContainerKind_CONTAINER_KIND_SIDECAR,
	"CONTAINER_KIND_APP":         ContainerKind_CONTAINER_KIND_APP,
	"CONTAINER_KIND_EPHEMERAL":   ContainerKind_CONTAINER_KIND_EPHEMERAL,
}

func (x ContainerKind) MarshalJSON() ([]byte, error) {
	if s, ok := containerKindToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *ContainerKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := containerKindFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown ContainerKind value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = ContainerKind(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into ContainerKind", string(data))
}

var containerStateToJSON = map[ContainerState]string{
	ContainerState_CONTAINER_STATE_UNSPECIFIED: "CONTAINER_STATE_UNSPECIFIED",
	ContainerState_CONTAINER_STATE_WAITING:     "waiting",
	ContainerState_CONTAINER_STATE_RUNNING:     "running",
	ContainerState_CONTAINER_STATE_TERMINATED:  "terminated",
}

var containerStateFromJSON = map[string]ContainerState{
	"CONTAINER_STATE_UNSPECIFIED": ContainerState_CONTAINER_STATE_UNSPECIFIED,
	"waiting":                     ContainerState_CONTAINER_STATE_WAITING,
	"running":                     ContainerState_CONTAINER_STATE_RUNNING,
	"terminated":                  ContainerState_CONTAINER_STATE_TERMINATED,
	"CONTAINER_STATE_WAITING":     ContainerState_CONTAINER_STATE_WAITING,
	"CONTAINER_STATE_RUNNING":     ContainerState_CONTAINER_STATE_RUNNING,
	"CONTAINER_STATE_TERMINATED":  ContainerState_CONTAINER_STATE_TERMINATED,
}

func (x ContainerState) MarshalJSON() ([]byte, error) {
	if s, ok := containerStateToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *ContainerState) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := containerStateFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown ContainerState value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = ContainerState(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into ContainerState", string(data))
}

var artifactKindToJSON = map[ArtifactKind]string{
	ArtifactKind_ARTIFACT_KIND_UNSPECIFIED:  "ARTIFACT_KIND_UNSPECIFIED",
	ArtifactKind_ARTIFACT_KIND_LOG_PREVIOUS: "log_previous",
	ArtifactKind_ARTIFACT_KIND_LOG_CURRENT:  "log_current",
	ArtifactKind_ARTIFACT_KIND_POD_JSON:     "pod_json",
}

var artifactKindFromJSON = map[string]ArtifactKind{
	"ARTIFACT_KIND_UNSPECIFIED":  ArtifactKind_ARTIFACT_KIND_UNSPECIFIED,
	"log_previous":               ArtifactKind_ARTIFACT_KIND_LOG_PREVIOUS,
	"log_current":                ArtifactKind_ARTIFACT_KIND_LOG_CURRENT,
	"pod_json":                   ArtifactKind_ARTIFACT_KIND_POD_JSON,
	"ARTIFACT_KIND_LOG_PREVIOUS": ArtifactKind_ARTIFACT_KIND_LOG_PREVIOUS,
	"ARTIFACT_KIND_LOG_CURRENT":  ArtifactKind_ARTIFACT_KIND_LOG_CURRENT,
	"ARTIFACT_KIND_POD_JSON":     ArtifactKind_ARTIFACT_KIND_POD_JSON,
}

func (x ArtifactKind) MarshalJSON() ([]byte, error) {
	if s, ok := artifactKindToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *ArtifactKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := artifactKindFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown ArtifactKind value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = ArtifactKind(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into ArtifactKind", string(data))
}

var subjectKindToJSON = map[SubjectKind]string{
	SubjectKind_SUBJECT_KIND_UNSPECIFIED: "SUBJECT_KIND_UNSPECIFIED",
	SubjectKind_SUBJECT_KIND_POD:         "pod",
	SubjectKind_SUBJECT_KIND_JOB:         "job",
}

var subjectKindFromJSON = map[string]SubjectKind{
	"SUBJECT_KIND_UNSPECIFIED": SubjectKind_SUBJECT_KIND_UNSPECIFIED,
	"pod":                      SubjectKind_SUBJECT_KIND_POD,
	"job":                      SubjectKind_SUBJECT_KIND_JOB,
	"SUBJECT_KIND_POD":         SubjectKind_SUBJECT_KIND_POD,
	"SUBJECT_KIND_JOB":         SubjectKind_SUBJECT_KIND_JOB,
}

func (x SubjectKind) MarshalJSON() ([]byte, error) {
	if s, ok := subjectKindToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *SubjectKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := subjectKindFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown SubjectKind value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = SubjectKind(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into SubjectKind", string(data))
}

var timelineKindToJSON = map[TimelineKind]string{
	TimelineKind_TIMELINE_KIND_UNSPECIFIED:          "TIMELINE_KIND_UNSPECIFIED",
	TimelineKind_TIMELINE_KIND_CONTAINER_TRANSITION: "container_transition",
	TimelineKind_TIMELINE_KIND_CONDITION:            "condition",
	TimelineKind_TIMELINE_KIND_EVENT:                "event",
	TimelineKind_TIMELINE_KIND_CAPTURE:              "capture",
	TimelineKind_TIMELINE_KIND_ROLLOUT:              "rollout",
	TimelineKind_TIMELINE_KIND_LIFECYCLE:            "lifecycle",
	TimelineKind_TIMELINE_KIND_CUT:                  "cut",
}

var timelineKindFromJSON = map[string]TimelineKind{
	"TIMELINE_KIND_UNSPECIFIED":          TimelineKind_TIMELINE_KIND_UNSPECIFIED,
	"container_transition":               TimelineKind_TIMELINE_KIND_CONTAINER_TRANSITION,
	"condition":                          TimelineKind_TIMELINE_KIND_CONDITION,
	"event":                              TimelineKind_TIMELINE_KIND_EVENT,
	"capture":                            TimelineKind_TIMELINE_KIND_CAPTURE,
	"rollout":                            TimelineKind_TIMELINE_KIND_ROLLOUT,
	"lifecycle":                          TimelineKind_TIMELINE_KIND_LIFECYCLE,
	"cut":                                TimelineKind_TIMELINE_KIND_CUT,
	"TIMELINE_KIND_CONTAINER_TRANSITION": TimelineKind_TIMELINE_KIND_CONTAINER_TRANSITION,
	"TIMELINE_KIND_CONDITION":            TimelineKind_TIMELINE_KIND_CONDITION,
	"TIMELINE_KIND_EVENT":                TimelineKind_TIMELINE_KIND_EVENT,
	"TIMELINE_KIND_CAPTURE":              TimelineKind_TIMELINE_KIND_CAPTURE,
	"TIMELINE_KIND_ROLLOUT":              TimelineKind_TIMELINE_KIND_ROLLOUT,
	"TIMELINE_KIND_LIFECYCLE":            TimelineKind_TIMELINE_KIND_LIFECYCLE,
	"TIMELINE_KIND_CUT":                  TimelineKind_TIMELINE_KIND_CUT,
}

func (x TimelineKind) MarshalJSON() ([]byte, error) {
	if s, ok := timelineKindToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *TimelineKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := timelineKindFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown TimelineKind value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = TimelineKind(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into TimelineKind", string(data))
}

var lifecycleStepToJSON = map[LifecycleStep]string{
	LifecycleStep_LIFECYCLE_STEP_UNSPECIFIED: "LIFECYCLE_STEP_UNSPECIFIED",
	LifecycleStep_LIFECYCLE_STEP_OPENED:      "opened",
	LifecycleStep_LIFECYCLE_STEP_CLOSED:      "closed",
}

var lifecycleStepFromJSON = map[string]LifecycleStep{
	"LIFECYCLE_STEP_UNSPECIFIED": LifecycleStep_LIFECYCLE_STEP_UNSPECIFIED,
	"opened":                     LifecycleStep_LIFECYCLE_STEP_OPENED,
	"closed":                     LifecycleStep_LIFECYCLE_STEP_CLOSED,
	"LIFECYCLE_STEP_OPENED":      LifecycleStep_LIFECYCLE_STEP_OPENED,
	"LIFECYCLE_STEP_CLOSED":      LifecycleStep_LIFECYCLE_STEP_CLOSED,
}

func (x LifecycleStep) MarshalJSON() ([]byte, error) {
	if s, ok := lifecycleStepToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *LifecycleStep) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := lifecycleStepFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown LifecycleStep value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = LifecycleStep(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into LifecycleStep", string(data))
}
