// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: idios/v1/common.proto

package idiosv1

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for StateCount.
// This method handles enum_value fields and nested messages: state
func (x *StateCount) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite state to custom enum_value strings
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := incidentStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(incidentStateToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for StateCount.
func (x *StateCount) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for StateCount.
// This method handles enum_value fields and nested messages: state
func (x *StateCount) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite state from custom enum_value strings to proto names
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := incidentStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for StateCount.
func (x *StateCount) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for CategoryCount.
// This method handles enum_value fields and nested messages: category
func (x *CategoryCount) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite category to custom enum_value strings
	for _, k := range []string{"category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(categoryToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for CategoryCount.
func (x *CategoryCount) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for CategoryCount.
// This method handles enum_value fields and nested messages: category
func (x *CategoryCount) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite category from custom enum_value strings to proto names
	for _, k := range []string{"category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for CategoryCount.
func (x *CategoryCount) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for Pod.
// This method handles enum_value fields and nested messages: deletion_source, deletion_reason
func (x *Pod) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite deletion_source to custom enum_value strings
	for _, k := range []string{"deletionSource", "deletion_source"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionSourceFromJSON[s]; ok {
			raw[k], _ = json.Marshal(deletionSourceToJSON[e])
		}
	}

	// Rewrite deletion_reason to custom enum_value strings
	for _, k := range []string{"deletionReason", "deletion_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(deletionReasonToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for Pod.
func (x *Pod) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for Pod.
// This method handles enum_value fields and nested messages: deletion_source, deletion_reason
func (x *Pod) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite deletion_source from custom enum_value strings to proto names
	for _, k := range []string{"deletionSource", "deletion_source"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionSourceFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite deletion_reason from custom enum_value strings to proto names
	for _, k := range []string{"deletionReason", "deletion_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for Pod.
func (x *Pod) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for Container.
// This method handles enum_value fields and nested messages: kind, state
func (x *Container) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite kind to custom enum_value strings
	for _, k := range []string{"kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(containerKindToJSON[e])
		}
	}

	// Rewrite state to custom enum_value strings
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(containerStateToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for Container.
func (x *Container) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for Container.
// This method handles enum_value fields and nested messages: kind, state
func (x *Container) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite kind from custom enum_value strings to proto names
	for _, k := range []string{"kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite state from custom enum_value strings to proto names
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for Container.
func (x *Container) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for K8SEvent.
// This method handles enum_value fields and nested messages: category
func (x *K8SEvent) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite category to custom enum_value strings
	for _, k := range []string{"category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(categoryToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for K8SEvent.
func (x *K8SEvent) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for K8SEvent.
// This method handles enum_value fields and nested messages: category
func (x *K8SEvent) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite category from custom enum_value strings to proto names
	for _, k := range []string{"category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for K8SEvent.
func (x *K8SEvent) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for ContainerStateHistory.
// This method handles enum_value fields and nested messages: state, category
func (x *ContainerStateHistory) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite state to custom enum_value strings
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(containerStateToJSON[e])
		}
	}

	// Rewrite category to custom enum_value strings
	for _, k := range []string{"category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(categoryToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for ContainerStateHistory.
func (x *ContainerStateHistory) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for ContainerStateHistory.
// This method handles enum_value fields and nested messages: state, category
func (x *ContainerStateHistory) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite state from custom enum_value strings to proto names
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite category from custom enum_value strings to proto names
	for _, k := range []string{"category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for ContainerStateHistory.
func (x *ContainerStateHistory) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
