// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: idios/v1/incidents.proto

package idiosv1

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for IncidentRow.
// This method handles enum_value fields and nested messages: subject_kind, category, close_reason, state, pod_deletion_reason
func (x *IncidentRow) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite subject_kind to custom enum_value strings
	for _, k := range []string{"subjectKind", "subject_kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := subjectKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(subjectKindToJSON[e])
		}
	}

	// Rewrite category to custom enum_value strings
	for _, k := range []string{"category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(categoryToJSON[e])
		}
	}

	// Rewrite close_reason to custom enum_value strings
	for _, k := range []string{"closeReason", "close_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := closeReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(closeReasonToJSON[e])
		}
	}

	// Rewrite state to custom enum_value strings
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := incidentStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(incidentStateToJSON[e])
		}
	}

	// Rewrite pod_deletion_reason to custom enum_value strings
	for _, k := range []string{"podDeletionReason", "pod_deletion_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(deletionReasonToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for IncidentRow.
func (x *IncidentRow) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for IncidentRow.
// This method handles enum_value fields and nested messages: subject_kind, category, close_reason, state, pod_deletion_reason
func (x *IncidentRow) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite subject_kind from custom enum_value strings to proto names
	for _, k := range []string{"subjectKind", "subject_kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := subjectKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite category from custom enum_value strings to proto names
	for _, k := range []string{"category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite close_reason from custom enum_value strings to proto names
	for _, k := range []string{"closeReason", "close_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := closeReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite state from custom enum_value strings to proto names
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := incidentStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite pod_deletion_reason from custom enum_value strings to proto names
	for _, k := range []string{"podDeletionReason", "pod_deletion_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for IncidentRow.
func (x *IncidentRow) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for IncidentsResponse.
// This method handles enum_value fields and nested messages: incidents
func (x *IncidentsResponse) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "incidents" forwarding opts to each element
	if len(x.Incidents) > 0 {
		items := make([]json.RawMessage, 0, len(x.Incidents))
		for _, item := range x.Incidents {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"incidents"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for IncidentsResponse.
func (x *IncidentsResponse) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for IncidentsResponse.
// This method handles enum_value fields and nested messages: incidents
func (x *IncidentsResponse) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "incidents" using its custom unmarshaler
	for _, k := range []string{"incidents"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &IncidentRow{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for IncidentsResponse.
func (x *IncidentsResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for IncidentCounts.
// This method handles enum_value fields and nested messages: by_state, by_category
func (x *IncidentCounts) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "byState" forwarding opts to each element
	if len(x.ByState) > 0 {
		items := make([]json.RawMessage, 0, len(x.ByState))
		for _, item := range x.ByState {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"byState", "by_state"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	// Re-serialize repeated "byCategory" forwarding opts to each element
	if len(x.ByCategory) > 0 {
		items := make([]json.RawMessage, 0, len(x.ByCategory))
		for _, item := range x.ByCategory {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"byCategory", "by_category"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for IncidentCounts.
func (x *IncidentCounts) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for IncidentCounts.
// This method handles enum_value fields and nested messages: by_state, by_category
func (x *IncidentCounts) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "byState" using its custom unmarshaler
	for _, k := range []string{"byState", "by_state"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &StateCount{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Handle "byCategory" using its custom unmarshaler
	for _, k := range []string{"byCategory", "by_category"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &CategoryCount{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for IncidentCounts.
func (x *IncidentCounts) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for SiblingPod.
// This method handles enum_value fields and nested messages: worst_open_category
func (x *SiblingPod) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite worst_open_category to custom enum_value strings
	for _, k := range []string{"worstOpenCategory", "worst_open_category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(categoryToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for SiblingPod.
func (x *SiblingPod) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for SiblingPod.
// This method handles enum_value fields and nested messages: worst_open_category
func (x *SiblingPod) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite worst_open_category from custom enum_value strings to proto names
	for _, k := range []string{"worstOpenCategory", "worst_open_category"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := categoryFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for SiblingPod.
func (x *SiblingPod) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for IncidentDetail.
// This method handles enum_value fields and nested messages: incident, pod, containers, artifacts, events, related_incidents
func (x *IncidentDetail) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize "incident" forwarding opts when child supports MarshalJSONSebuf
	if x.Incident != nil {
		if m, ok := any(x.Incident).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			childData, childErr := m.MarshalJSONSebuf(opts)
			if childErr != nil {
				return nil, childErr
			}
			for _, k := range []string{"incident"} {
				if _, ok := raw[k]; ok {
					raw[k] = childData
				}
			}
		}
	}

	// Re-serialize "pod" forwarding opts when child supports MarshalJSONSebuf
	if x.Pod != nil {
		if m, ok := any(x.Pod).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			childData, childErr := m.MarshalJSONSebuf(opts)
			if childErr != nil {
				return nil, childErr
			}
			for _, k := range []string{"pod"} {
				if _, ok := raw[k]; ok {
					raw[k] = childData
				}
			}
		}
	}

	// Re-serialize repeated "containers" forwarding opts to each element
	if len(x.Containers) > 0 {
		items := make([]json.RawMessage, 0, len(x.Containers))
		for _, item := range x.Containers {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"containers"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	// Re-serialize repeated "artifacts" forwarding opts to each element
	if len(x.Artifacts) > 0 {
		items := make([]json.RawMessage, 0, len(x.Artifacts))
		for _, item := range x.Artifacts {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"artifacts"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	// Re-serialize repeated "events" forwarding opts to each element
	if len(x.Events) > 0 {
		items := make([]json.RawMessage, 0, len(x.Events))
		for _, item := range x.Events {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"events"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	// Re-serialize repeated "relatedIncidents" forwarding opts to each element
	if len(x.RelatedIncidents) > 0 {
		items := make([]json.RawMessage, 0, len(x.RelatedIncidents))
		for _, item := range x.RelatedIncidents {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"relatedIncidents", "related_incidents"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for IncidentDetail.
func (x *IncidentDetail) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for IncidentDetail.
// This method handles enum_value fields and nested messages: incident, pod, containers, artifacts, events, related_incidents
func (x *IncidentDetail) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "incident" using its custom unmarshaler
	for _, k := range []string{"incident"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		inner := &IncidentRow{}
		if u, ok := any(inner).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(rawVal, opts); err != nil {
				return err
			}
		} else if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, marshalErr := protojson.Marshal(inner)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = innerJSON
	}

	// Handle "pod" using its custom unmarshaler
	for _, k := range []string{"pod"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		inner := &Pod{}
		if u, ok := any(inner).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(rawVal, opts); err != nil {
				return err
			}
		} else if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, marshalErr := protojson.Marshal(inner)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = innerJSON
	}

	// Handle "containers" using its custom unmarshaler
	for _, k := range []string{"containers"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &Container{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Handle "artifacts" using its custom unmarshaler
	for _, k := range []string{"artifacts"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &Artifact{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Handle "events" using its custom unmarshaler
	for _, k := range []string{"events"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &K8SEvent{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Handle "relatedIncidents" using its custom unmarshaler
	for _, k := range []string{"relatedIncidents", "related_incidents"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &IncidentRow{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for IncidentDetail.
func (x *IncidentDetail) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for TimelineEntry.
// This method handles enum_value fields and nested messages: kind, state, artifact_kind, capture_gap, lifecycle, close_reason
func (x *TimelineEntry) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite kind to custom enum_value strings
	for _, k := range []string{"kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := timelineKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(timelineKindToJSON[e])
		}
	}

	// Rewrite state to custom enum_value strings
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(containerStateToJSON[e])
		}
	}

	// Rewrite artifact_kind to custom enum_value strings
	for _, k := range []string{"artifactKind", "artifact_kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := artifactKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(artifactKindToJSON[e])
		}
	}

	// Rewrite capture_gap to custom enum_value strings
	for _, k := range []string{"captureGap", "capture_gap"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := captureGapFromJSON[s]; ok {
			raw[k], _ = json.Marshal(captureGapToJSON[e])
		}
	}

	// Rewrite lifecycle to custom enum_value strings
	for _, k := range []string{"lifecycle"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := lifecycleStepFromJSON[s]; ok {
			raw[k], _ = json.Marshal(lifecycleStepToJSON[e])
		}
	}

	// Rewrite close_reason to custom enum_value strings
	for _, k := range []string{"closeReason", "close_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := closeReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(closeReasonToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for TimelineEntry.
func (x *TimelineEntry) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for TimelineEntry.
// This method handles enum_value fields and nested messages: kind, state, artifact_kind, capture_gap, lifecycle, close_reason
func (x *TimelineEntry) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite kind from custom enum_value strings to proto names
	for _, k := range []string{"kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := timelineKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite state from custom enum_value strings to proto names
	for _, k := range []string{"state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite artifact_kind from custom enum_value strings to proto names
	for _, k := range []string{"artifactKind", "artifact_kind"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := artifactKindFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite capture_gap from custom enum_value strings to proto names
	for _, k := range []string{"captureGap", "capture_gap"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := captureGapFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite lifecycle from custom enum_value strings to proto names
	for _, k := range []string{"lifecycle"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := lifecycleStepFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite close_reason from custom enum_value strings to proto names
	for _, k := range []string{"closeReason", "close_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := closeReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for TimelineEntry.
func (x *TimelineEntry) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for TimelineResponse.
// This method handles enum_value fields and nested messages: entries
func (x *TimelineResponse) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "entries" forwarding opts to each element
	if len(x.Entries) > 0 {
		items := make([]json.RawMessage, 0, len(x.Entries))
		for _, item := range x.Entries {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"entries"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for TimelineResponse.
func (x *TimelineResponse) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for TimelineResponse.
// This method handles enum_value fields and nested messages: entries
func (x *TimelineResponse) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "entries" using its custom unmarshaler
	for _, k := range []string{"entries"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &TimelineEntry{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for TimelineResponse.
func (x *TimelineResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
