// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: idios/v1/pods.proto

package idiosv1

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for PodRow.
// This method handles enum_value fields and nested messages: deletion_source, deletion_reason, worst_state
func (x *PodRow) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite deletion_source to custom enum_value strings
	for _, k := range []string{"deletionSource", "deletion_source"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionSourceFromJSON[s]; ok {
			raw[k], _ = json.Marshal(deletionSourceToJSON[e])
		}
	}

	// Rewrite deletion_reason to custom enum_value strings
	for _, k := range []string{"deletionReason", "deletion_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(deletionReasonToJSON[e])
		}
	}

	// Rewrite worst_state to custom enum_value strings
	for _, k := range []string{"worstState", "worst_state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(containerStateToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for PodRow.
func (x *PodRow) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for PodRow.
// This method handles enum_value fields and nested messages: deletion_source, deletion_reason, worst_state
func (x *PodRow) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite deletion_source from custom enum_value strings to proto names
	for _, k := range []string{"deletionSource", "deletion_source"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionSourceFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite deletion_reason from custom enum_value strings to proto names
	for _, k := range []string{"deletionReason", "deletion_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := deletionReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Rewrite worst_state from custom enum_value strings to proto names
	for _, k := range []string{"worstState", "worst_state"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := containerStateFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for PodRow.
func (x *PodRow) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for PodsResponse.
// This method handles enum_value fields and nested messages: pods
func (x *PodsResponse) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "pods" forwarding opts to each element
	if len(x.Pods) > 0 {
		items := make([]json.RawMessage, 0, len(x.Pods))
		for _, item := range x.Pods {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"pods"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for PodsResponse.
func (x *PodsResponse) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for PodsResponse.
// This method handles enum_value fields and nested messages: pods
func (x *PodsResponse) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "pods" using its custom unmarshaler
	for _, k := range []string{"pods"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &PodRow{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for PodsResponse.
func (x *PodsResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for PodDetail.
// This method handles enum_value fields and nested messages: pod, containers, incidents, artifacts, siblings
func (x *PodDetail) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize "pod" forwarding opts when child supports MarshalJSONSebuf
	if x.Pod != nil {
		if m, ok := any(x.Pod).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			childData, childErr := m.MarshalJSONSebuf(opts)
			if childErr != nil {
				return nil, childErr
			}
			for _, k := range []string{"pod"} {
				if _, ok := raw[k]; ok {
					raw[k] = childData
				}
			}
		}
	}

	// Re-serialize repeated "containers" forwarding opts to each element
	if len(x.Containers) > 0 {
		items := make([]json.RawMessage, 0, len(x.Containers))
		for _, item := range x.Containers {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"containers"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	// Re-serialize repeated "incidents" forwarding opts to each element
	if len(x.Incidents) > 0 {
		items := make([]json.RawMessage, 0, len(x.Incidents))
		for _, item := range x.Incidents {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"incidents"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	// Re-serialize repeated "artifacts" forwarding opts to each element
	if len(x.Artifacts) > 0 {
		items := make([]json.RawMessage, 0, len(x.Artifacts))
		for _, item := range x.Artifacts {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"artifacts"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	// Re-serialize repeated "siblings" forwarding opts to each element
	if len(x.Siblings) > 0 {
		items := make([]json.RawMessage, 0, len(x.Siblings))
		for _, item := range x.Siblings {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"siblings"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for PodDetail.
func (x *PodDetail) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for PodDetail.
// This method handles enum_value fields and nested messages: pod, containers, incidents, artifacts, siblings
func (x *PodDetail) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "pod" using its custom unmarshaler
	for _, k := range []string{"pod"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		inner := &PodRow{}
		if u, ok := any(inner).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(rawVal, opts); err != nil {
				return err
			}
		} else if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, marshalErr := protojson.Marshal(inner)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = innerJSON
	}

	// Handle "containers" using its custom unmarshaler
	for _, k := range []string{"containers"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &Container{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Handle "incidents" using its custom unmarshaler
	for _, k := range []string{"incidents"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &IncidentRow{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Handle "artifacts" using its custom unmarshaler
	for _, k := range []string{"artifacts"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &Artifact{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Handle "siblings" using its custom unmarshaler
	for _, k := range []string{"siblings"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &SiblingPod{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for PodDetail.
func (x *PodDetail) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for EventsResponse.
// This method handles enum_value fields and nested messages: events
func (x *EventsResponse) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "events" forwarding opts to each element
	if len(x.Events) > 0 {
		items := make([]json.RawMessage, 0, len(x.Events))
		for _, item := range x.Events {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"events"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for EventsResponse.
func (x *EventsResponse) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for EventsResponse.
// This method handles enum_value fields and nested messages: events
func (x *EventsResponse) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "events" using its custom unmarshaler
	for _, k := range []string{"events"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &K8SEvent{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for EventsResponse.
func (x *EventsResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for HistoryResponse.
// This method handles enum_value fields and nested messages: transitions
func (x *HistoryResponse) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "transitions" forwarding opts to each element
	if len(x.Transitions) > 0 {
		items := make([]json.RawMessage, 0, len(x.Transitions))
		for _, item := range x.Transitions {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"transitions"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for HistoryResponse.
func (x *HistoryResponse) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for HistoryResponse.
// This method handles enum_value fields and nested messages: transitions
func (x *HistoryResponse) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "transitions" using its custom unmarshaler
	for _, k := range []string{"transitions"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &ContainerStateHistory{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for HistoryResponse.
func (x *HistoryResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
