// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: idios/v1/service.proto

package idiosv1

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// sebufUnmarshaler is implemented by generated messages with custom JSON unmarshaling.
// It allows passing protojson.UnmarshalOptions (e.g. DiscardUnknown) through custom unmarshalers.
type sebufUnmarshaler interface {
	UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error
}

// IdiosServiceClient is the client API for IdiosService service.
type IdiosServiceClient interface {
	ListClusters(ctx context.Context, req *ListClustersRequest, opts ...IdiosServiceCallOption) (*ClustersResponse, error)
	ListKubeContexts(ctx context.Context, req *ListKubeContextsRequest, opts ...IdiosServiceCallOption) (*KubeContextsResponse, error)
	ListKubeNamespaces(ctx context.Context, req *ListKubeNamespacesRequest, opts ...IdiosServiceCallOption) (*KubeNamespacesResponse, error)
	ListIncidents(ctx context.Context, req *ListIncidentsRequest, opts ...IdiosServiceCallOption) (*IncidentsResponse, error)
	GetIncidentCounts(ctx context.Context, req *GetIncidentCountsRequest, opts ...IdiosServiceCallOption) (*IncidentCounts, error)
	GetIncident(ctx context.Context, req *GetIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentDetail, error)
	IncidentTimeline(ctx context.Context, req *IncidentTimelineRequest, opts ...IdiosServiceCallOption) (*TimelineResponse, error)
	StreamIncidents(ctx context.Context, req *StreamIncidentsRequest, opts ...IdiosServiceCallOption) (*IdiosServiceEventStream[*IncidentRow], error)
	StreamClusters(ctx context.Context, req *StreamClustersRequest, opts ...IdiosServiceCallOption) (*IdiosServiceEventStream[*Cluster], error)
	ListPods(ctx context.Context, req *ListPodsRequest, opts ...IdiosServiceCallOption) (*PodsResponse, error)
	GetPod(ctx context.Context, req *GetPodRequest, opts ...IdiosServiceCallOption) (*PodDetail, error)
	PodEvents(ctx context.Context, req *PodEventsRequest, opts ...IdiosServiceCallOption) (*EventsResponse, error)
	PodHistory(ctx context.Context, req *PodHistoryRequest, opts ...IdiosServiceCallOption) (*HistoryResponse, error)
	GetArtifact(ctx context.Context, req *GetArtifactRequest, opts ...IdiosServiceCallOption) (*Artifact, error)
	ListWorkloads(ctx context.Context, req *ListWorkloadsRequest, opts ...IdiosServiceCallOption) (*WorkloadsResponse, error)
	GetWorkload(ctx context.Context, req *GetWorkloadRequest, opts ...IdiosServiceCallOption) (*WorkloadDetail, error)
	ListJobs(ctx context.Context, req *ListJobsRequest, opts ...IdiosServiceCallOption) (*JobsResponse, error)
	GetStatus(ctx context.Context, req *GetStatusRequest, opts ...IdiosServiceCallOption) (*Status, error)
	AcknowledgeIncident(ctx context.Context, req *AcknowledgeIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error)
	UnacknowledgeIncident(ctx context.Context, req *UnacknowledgeIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error)
	ResolveIncident(ctx context.Context, req *ResolveIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error)
	UnresolveIncident(ctx context.Context, req *UnresolveIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error)
	DismissIncident(ctx context.Context, req *DismissIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error)
	UndismissIncident(ctx context.Context, req *UndismissIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error)
	SetIncidentNote(ctx context.Context, req *SetIncidentNoteRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error)
	DeleteIncident(ctx context.Context, req *DeleteIncidentRequest, opts ...IdiosServiceCallOption) (*DeleteIncidentResponse, error)
	AddCluster(ctx context.Context, req *AddClusterRequest, opts ...IdiosServiceCallOption) (*Cluster, error)
	RenameCluster(ctx context.Context, req *RenameClusterRequest, opts ...IdiosServiceCallOption) (*Cluster, error)
	SetClusterGrafana(ctx context.Context, req *SetClusterGrafanaRequest, opts ...IdiosServiceCallOption) (*Cluster, error)
	DeleteCluster(ctx context.Context, req *DeleteClusterRequest, opts ...IdiosServiceCallOption) (*DeleteClusterResponse, error)
	AddWatchedNamespace(ctx context.Context, req *AddWatchedNamespaceRequest, opts ...IdiosServiceCallOption) (*Cluster, error)
	RemoveWatchedNamespace(ctx context.Context, req *RemoveWatchedNamespaceRequest, opts ...IdiosServiceCallOption) (*Cluster, error)
}

// idiosServiceClient is the implementation of IdiosServiceClient.
type idiosServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ IdiosServiceClient = (*idiosServiceClient)(nil)

// IdiosServiceClientOption configures a IdiosService client.
type IdiosServiceClientOption func(*idiosServiceClient)

// WithIdiosServiceHTTPClient sets the HTTP client to use for requests.
func WithIdiosServiceHTTPClient(client *http.Client) IdiosServiceClientOption {
	return func(c *idiosServiceClient) {
		c.httpClient = client
	}
}

// WithIdiosServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithIdiosServiceContentType(contentType string) IdiosServiceClientOption {
	return func(c *idiosServiceClient) {
		c.contentType = contentType
	}
}

// WithIdiosServiceDefaultHeader sets a default header to include in all requests.
func WithIdiosServiceDefaultHeader(key, value string) IdiosServiceClientOption {
	return func(c *idiosServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithIdiosServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithIdiosServiceDiscardUnknownFields(discard bool) IdiosServiceClientOption {
	return func(c *idiosServiceClient) {
		c.discardUnknownFields = discard
	}
}

// IdiosServiceCallOption configures a single RPC call.
type IdiosServiceCallOption func(*idiosServiceCallOptions)

// idiosServiceCallOptions holds options for a single RPC call.
type idiosServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithIdiosServiceHeader adds a header to a single request.
func WithIdiosServiceHeader(key, value string) IdiosServiceCallOption {
	return func(o *idiosServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithIdiosServiceCallContentType sets the content type for a single request.
func WithIdiosServiceCallContentType(contentType string) IdiosServiceCallOption {
	return func(o *idiosServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithIdiosServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithIdiosServiceDiscardUnknownFields.
func WithIdiosServiceCallDiscardUnknownFields(discard bool) IdiosServiceCallOption {
	return func(o *idiosServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewIdiosServiceClient creates a new IdiosService client.
func NewIdiosServiceClient(baseURL string, opts ...IdiosServiceClientOption) IdiosServiceClient {
	c := &idiosServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// IdiosServiceEventStream reads Server-Sent Events from a streaming endpoint.
type IdiosServiceEventStream[T proto.Message] struct {
	resp                 *http.Response
	reader               *bufio.Reader
	err                  error
	discardUnknownFields bool
}

// Next reads the next event from the stream.
// Returns false when the stream ends or an error occurs.
func (s *IdiosServiceEventStream[T]) Next(event T) bool {
	for {
		line, err := s.reader.ReadString('\n')
		if err != nil {
			if err != io.EOF {
				s.err = err
			}
			return false
		}
		line = strings.TrimRight(line, "\r\n")
		if !strings.HasPrefix(line, "data: ") {
			continue
		}
		data := strings.TrimPrefix(line, "data: ")
		opts := protojson.UnmarshalOptions{DiscardUnknown: s.discardUnknownFields}
		var unmarshalErr error
		if u, ok := any(event).(sebufUnmarshaler); ok {
			unmarshalErr = u.UnmarshalJSONSebuf([]byte(data), opts)
		} else if u, ok := any(event).(json.Unmarshaler); ok {
			unmarshalErr = u.UnmarshalJSON([]byte(data))
		} else {
			unmarshalErr = opts.Unmarshal([]byte(data), event)
		}
		if unmarshalErr != nil {
			s.err = fmt.Errorf("failed to unmarshal SSE event: %w", unmarshalErr)
			return false
		}
		return true
	}
}

// Err returns any error encountered during streaming.
func (s *IdiosServiceEventStream[T]) Err() error {
	return s.err
}

// Close closes the underlying HTTP response body.
func (s *IdiosServiceEventStream[T]) Close() error {
	return s.resp.Body.Close()
}

// ListClusters calls the ListClusters RPC.
func (c *idiosServiceClient) ListClusters(ctx context.Context, req *ListClustersRequest, opts ...IdiosServiceCallOption) (*ClustersResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/clusters"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	for _, v := range req.ClusterIds {
		queryParams.Add("cluster_ids", fmt.Sprint(v))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &ClustersResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// ListKubeContexts calls the ListKubeContexts RPC.
func (c *idiosServiceClient) ListKubeContexts(ctx context.Context, req *ListKubeContextsRequest, opts ...IdiosServiceCallOption) (*KubeContextsResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/kube/contexts"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &KubeContextsResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// ListKubeNamespaces calls the ListKubeNamespaces RPC.
func (c *idiosServiceClient) ListKubeNamespaces(ctx context.Context, req *ListKubeNamespacesRequest, opts ...IdiosServiceCallOption) (*KubeNamespacesResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/kube/contexts/{context}/namespaces"
	path = strings.Replace(path, "{context}", url.PathEscape(fmt.Sprint(req.Context)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &KubeNamespacesResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// ListIncidents calls the ListIncidents RPC.
func (c *idiosServiceClient) ListIncidents(ctx context.Context, req *ListIncidentsRequest, opts ...IdiosServiceCallOption) (*IncidentsResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	for _, v := range req.ClusterIds {
		queryParams.Add("cluster_ids", fmt.Sprint(v))
	}
	if req.State != "" {
		queryParams.Set("state", fmt.Sprint(req.State))
	}
	if req.Category != "" {
		queryParams.Set("category", fmt.Sprint(req.Category))
	}
	if req.Namespace != "" {
		queryParams.Set("namespace", fmt.Sprint(req.Namespace))
	}
	if req.WorkloadKind != "" {
		queryParams.Set("workload_kind", fmt.Sprint(req.WorkloadKind))
	}
	if req.WorkloadName != "" {
		queryParams.Set("workload_name", fmt.Sprint(req.WorkloadName))
	}
	if req.PodUid != "" {
		queryParams.Set("pod_uid", fmt.Sprint(req.PodUid))
	}
	if req.JobUid != "" {
		queryParams.Set("job_uid", fmt.Sprint(req.JobUid))
	}
	if req.Limit != 0 {
		queryParams.Set("limit", fmt.Sprint(req.Limit))
	}
	if req.NodeName != "" {
		queryParams.Set("node_name", fmt.Sprint(req.NodeName))
	}
	if req.PodName != "" {
		queryParams.Set("pod_name", fmt.Sprint(req.PodName))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentsResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetIncidentCounts calls the GetIncidentCounts RPC.
func (c *idiosServiceClient) GetIncidentCounts(ctx context.Context, req *GetIncidentCountsRequest, opts ...IdiosServiceCallOption) (*IncidentCounts, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/counts"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	for _, v := range req.ClusterIds {
		queryParams.Add("cluster_ids", fmt.Sprint(v))
	}
	if req.State != "" {
		queryParams.Set("state", fmt.Sprint(req.State))
	}
	if req.Category != "" {
		queryParams.Set("category", fmt.Sprint(req.Category))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentCounts{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetIncident calls the GetIncident RPC.
func (c *idiosServiceClient) GetIncident(ctx context.Context, req *GetIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentDetail, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentDetail{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// IncidentTimeline calls the IncidentTimeline RPC.
func (c *idiosServiceClient) IncidentTimeline(ctx context.Context, req *IncidentTimelineRequest, opts ...IdiosServiceCallOption) (*TimelineResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}/timeline"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &TimelineResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// StreamIncidents calls the StreamIncidents SSE streaming RPC.
func (c *idiosServiceClient) StreamIncidents(ctx context.Context, req *StreamIncidentsRequest, opts ...IdiosServiceCallOption) (*IdiosServiceEventStream[*IncidentRow], error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/stream"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	for _, v := range req.ClusterIds {
		queryParams.Add("cluster_ids", fmt.Sprint(v))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	httpReq.Header.Set("Accept", "text/event-stream")
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		defer resp.Body.Close()
		respBody, readErr := io.ReadAll(resp.Body)
		if readErr != nil {
			return nil, fmt.Errorf("failed to read error response: %w", readErr)
		}
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	return &IdiosServiceEventStream[*IncidentRow]{
		resp:                 resp,
		reader:               bufio.NewReader(resp.Body),
		discardUnknownFields: discardUnknown,
	}, nil
}

// StreamClusters calls the StreamClusters SSE streaming RPC.
func (c *idiosServiceClient) StreamClusters(ctx context.Context, req *StreamClustersRequest, opts ...IdiosServiceCallOption) (*IdiosServiceEventStream[*Cluster], error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/clusters/stream"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	for _, v := range req.ClusterIds {
		queryParams.Add("cluster_ids", fmt.Sprint(v))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	httpReq.Header.Set("Accept", "text/event-stream")
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		defer resp.Body.Close()
		respBody, readErr := io.ReadAll(resp.Body)
		if readErr != nil {
			return nil, fmt.Errorf("failed to read error response: %w", readErr)
		}
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	return &IdiosServiceEventStream[*Cluster]{
		resp:                 resp,
		reader:               bufio.NewReader(resp.Body),
		discardUnknownFields: discardUnknown,
	}, nil
}

// ListPods calls the ListPods RPC.
func (c *idiosServiceClient) ListPods(ctx context.Context, req *ListPodsRequest, opts ...IdiosServiceCallOption) (*PodsResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/pods"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	for _, v := range req.ClusterIds {
		queryParams.Add("cluster_ids", fmt.Sprint(v))
	}
	if req.Namespace != "" {
		queryParams.Set("namespace", fmt.Sprint(req.Namespace))
	}
	if req.WorkloadKind != "" {
		queryParams.Set("workload_kind", fmt.Sprint(req.WorkloadKind))
	}
	if req.WorkloadName != "" {
		queryParams.Set("workload_name", fmt.Sprint(req.WorkloadName))
	}
	if req.Live != "" {
		queryParams.Set("live", fmt.Sprint(req.Live))
	}
	if req.Limit != 0 {
		queryParams.Set("limit", fmt.Sprint(req.Limit))
	}
	if req.PodName != "" {
		queryParams.Set("pod_name", fmt.Sprint(req.PodName))
	}
	if req.JobUid != "" {
		queryParams.Set("job_uid", fmt.Sprint(req.JobUid))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &PodsResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetPod calls the GetPod RPC.
func (c *idiosServiceClient) GetPod(ctx context.Context, req *GetPodRequest, opts ...IdiosServiceCallOption) (*PodDetail, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/pods/{uid}"
	path = strings.Replace(path, "{uid}", url.PathEscape(fmt.Sprint(req.Uid)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &PodDetail{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// PodEvents calls the PodEvents RPC.
func (c *idiosServiceClient) PodEvents(ctx context.Context, req *PodEventsRequest, opts ...IdiosServiceCallOption) (*EventsResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/pods/{uid}/events"
	path = strings.Replace(path, "{uid}", url.PathEscape(fmt.Sprint(req.Uid)), 1)
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	if req.Limit != 0 {
		queryParams.Set("limit", fmt.Sprint(req.Limit))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &EventsResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// PodHistory calls the PodHistory RPC.
func (c *idiosServiceClient) PodHistory(ctx context.Context, req *PodHistoryRequest, opts ...IdiosServiceCallOption) (*HistoryResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/pods/{uid}/history"
	path = strings.Replace(path, "{uid}", url.PathEscape(fmt.Sprint(req.Uid)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &HistoryResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetArtifact calls the GetArtifact RPC.
func (c *idiosServiceClient) GetArtifact(ctx context.Context, req *GetArtifactRequest, opts ...IdiosServiceCallOption) (*Artifact, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/artifacts/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Artifact{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// ListWorkloads calls the ListWorkloads RPC.
func (c *idiosServiceClient) ListWorkloads(ctx context.Context, req *ListWorkloadsRequest, opts ...IdiosServiceCallOption) (*WorkloadsResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/workloads"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	for _, v := range req.ClusterIds {
		queryParams.Add("cluster_ids", fmt.Sprint(v))
	}
	if req.Namespace != "" {
		queryParams.Set("namespace", fmt.Sprint(req.Namespace))
	}
	if req.Limit != 0 {
		queryParams.Set("limit", fmt.Sprint(req.Limit))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &WorkloadsResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetWorkload calls the GetWorkload RPC.
func (c *idiosServiceClient) GetWorkload(ctx context.Context, req *GetWorkloadRequest, opts ...IdiosServiceCallOption) (*WorkloadDetail, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/workloads/{cluster_id}/{namespace}/{kind}/{name}"
	path = strings.Replace(path, "{cluster_id}", url.PathEscape(fmt.Sprint(req.ClusterId)), 1)
	path = strings.Replace(path, "{namespace}", url.PathEscape(fmt.Sprint(req.Namespace)), 1)
	path = strings.Replace(path, "{kind}", url.PathEscape(fmt.Sprint(req.Kind)), 1)
	path = strings.Replace(path, "{name}", url.PathEscape(fmt.Sprint(req.Name)), 1)
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	if req.PodsLive != "" {
		queryParams.Set("pods_live", fmt.Sprint(req.PodsLive))
	}
	if req.PodsLimit != 0 {
		queryParams.Set("pods_limit", fmt.Sprint(req.PodsLimit))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &WorkloadDetail{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// ListJobs calls the ListJobs RPC.
func (c *idiosServiceClient) ListJobs(ctx context.Context, req *ListJobsRequest, opts ...IdiosServiceCallOption) (*JobsResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/jobs"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	for _, v := range req.ClusterIds {
		queryParams.Add("cluster_ids", fmt.Sprint(v))
	}
	if req.Namespace != "" {
		queryParams.Set("namespace", fmt.Sprint(req.Namespace))
	}
	if req.CronjobUid != "" {
		queryParams.Set("cronjob_uid", fmt.Sprint(req.CronjobUid))
	}
	if req.Limit != 0 {
		queryParams.Set("limit", fmt.Sprint(req.Limit))
	}
	if req.CronjobName != "" {
		queryParams.Set("cronjob_name", fmt.Sprint(req.CronjobName))
	}
	if req.Live != "" {
		queryParams.Set("live", fmt.Sprint(req.Live))
	}
	if req.Failed != "" {
		queryParams.Set("failed", fmt.Sprint(req.Failed))
	}
	if req.JobUid != "" {
		queryParams.Set("job_uid", fmt.Sprint(req.JobUid))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &JobsResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetStatus calls the GetStatus RPC.
func (c *idiosServiceClient) GetStatus(ctx context.Context, req *GetStatusRequest, opts ...IdiosServiceCallOption) (*Status, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/status"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Status{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// AcknowledgeIncident calls the AcknowledgeIncident RPC.
func (c *idiosServiceClient) AcknowledgeIncident(ctx context.Context, req *AcknowledgeIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}/acknowledge"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentRow{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// UnacknowledgeIncident calls the UnacknowledgeIncident RPC.
func (c *idiosServiceClient) UnacknowledgeIncident(ctx context.Context, req *UnacknowledgeIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}/acknowledge"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "DELETE", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentRow{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// ResolveIncident calls the ResolveIncident RPC.
func (c *idiosServiceClient) ResolveIncident(ctx context.Context, req *ResolveIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}/resolve"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentRow{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// UnresolveIncident calls the UnresolveIncident RPC.
func (c *idiosServiceClient) UnresolveIncident(ctx context.Context, req *UnresolveIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}/resolve"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "DELETE", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentRow{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// DismissIncident calls the DismissIncident RPC.
func (c *idiosServiceClient) DismissIncident(ctx context.Context, req *DismissIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}/dismiss"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentRow{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// UndismissIncident calls the UndismissIncident RPC.
func (c *idiosServiceClient) UndismissIncident(ctx context.Context, req *UndismissIncidentRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}/dismiss"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "DELETE", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentRow{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// SetIncidentNote calls the SetIncidentNote RPC.
func (c *idiosServiceClient) SetIncidentNote(ctx context.Context, req *SetIncidentNoteRequest, opts ...IdiosServiceCallOption) (*IncidentRow, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}/note"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "PUT", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &IncidentRow{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// DeleteIncident calls the DeleteIncident RPC.
func (c *idiosServiceClient) DeleteIncident(ctx context.Context, req *DeleteIncidentRequest, opts ...IdiosServiceCallOption) (*DeleteIncidentResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/incidents/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "DELETE", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &DeleteIncidentResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// AddCluster calls the AddCluster RPC.
func (c *idiosServiceClient) AddCluster(ctx context.Context, req *AddClusterRequest, opts ...IdiosServiceCallOption) (*Cluster, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/clusters"
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Cluster{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// RenameCluster calls the RenameCluster RPC.
func (c *idiosServiceClient) RenameCluster(ctx context.Context, req *RenameClusterRequest, opts ...IdiosServiceCallOption) (*Cluster, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/clusters/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "PATCH", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Cluster{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// SetClusterGrafana calls the SetClusterGrafana RPC.
func (c *idiosServiceClient) SetClusterGrafana(ctx context.Context, req *SetClusterGrafanaRequest, opts ...IdiosServiceCallOption) (*Cluster, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/clusters/{id}/grafana"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "PATCH", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Cluster{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// DeleteCluster calls the DeleteCluster RPC.
func (c *idiosServiceClient) DeleteCluster(ctx context.Context, req *DeleteClusterRequest, opts ...IdiosServiceCallOption) (*DeleteClusterResponse, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/clusters/{id}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "DELETE", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &DeleteClusterResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// AddWatchedNamespace calls the AddWatchedNamespace RPC.
func (c *idiosServiceClient) AddWatchedNamespace(ctx context.Context, req *AddWatchedNamespaceRequest, opts ...IdiosServiceCallOption) (*Cluster, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/clusters/{id}/namespaces"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Marshal request body
	body, err := c.marshalRequest(req, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", reqURL, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Cluster{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// RemoveWatchedNamespace calls the RemoveWatchedNamespace RPC.
func (c *idiosServiceClient) RemoveWatchedNamespace(ctx context.Context, req *RemoveWatchedNamespaceRequest, opts ...IdiosServiceCallOption) (*Cluster, error) {
	callOpts := &idiosServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/v1/clusters/{id}/namespaces/{name}"
	path = strings.Replace(path, "{id}", url.PathEscape(fmt.Sprint(req.Id)), 1)
	path = strings.Replace(path, "{name}", url.PathEscape(fmt.Sprint(req.Name)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "DELETE", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &Cluster{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *idiosServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *idiosServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *idiosServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	opts := protojson.UnmarshalOptions{DiscardUnknown: discardUnknown}

	switch contentType {
	case ContentTypeJSON:
		// Check for sebuf-generated custom unmarshaler (passes options through)
		if u, ok := msg.(sebufUnmarshaler); ok {
			return u.UnmarshalJSONSebuf(body, opts)
		}
		// Check for third-party json.Unmarshaler (best effort, cannot pass options)
		if u, ok := msg.(json.Unmarshaler); ok {
			return u.UnmarshalJSON(body)
		}
		return opts.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		return opts.Unmarshal(body, msg)
	}
}
