// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: idios/v1/service.proto

package idiosv1

import (
	"context"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

// IdiosServiceServer is the server API for IdiosService service.
type IdiosServiceServer interface {
	ListClusters(context.Context, *ListClustersRequest) (*ClustersResponse, error)
	ListKubeContexts(context.Context, *ListKubeContextsRequest) (*KubeContextsResponse, error)
	ListKubeNamespaces(context.Context, *ListKubeNamespacesRequest) (*KubeNamespacesResponse, error)
	ListIncidents(context.Context, *ListIncidentsRequest) (*IncidentsResponse, error)
	GetIncidentCounts(context.Context, *GetIncidentCountsRequest) (*IncidentCounts, error)
	GetIncident(context.Context, *GetIncidentRequest) (*IncidentDetail, error)
	IncidentTimeline(context.Context, *IncidentTimelineRequest) (*TimelineResponse, error)
	StreamIncidents(context.Context, *StreamIncidentsRequest, SSESender) error
	StreamClusters(context.Context, *StreamClustersRequest, SSESender) error
	ListPods(context.Context, *ListPodsRequest) (*PodsResponse, error)
	GetPod(context.Context, *GetPodRequest) (*PodDetail, error)
	PodEvents(context.Context, *PodEventsRequest) (*EventsResponse, error)
	PodHistory(context.Context, *PodHistoryRequest) (*HistoryResponse, error)
	GetArtifact(context.Context, *GetArtifactRequest) (*Artifact, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*WorkloadsResponse, error)
	GetWorkload(context.Context, *GetWorkloadRequest) (*WorkloadDetail, error)
	ListJobs(context.Context, *ListJobsRequest) (*JobsResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*Status, error)
	AcknowledgeIncident(context.Context, *AcknowledgeIncidentRequest) (*IncidentRow, error)
	UnacknowledgeIncident(context.Context, *UnacknowledgeIncidentRequest) (*IncidentRow, error)
	ResolveIncident(context.Context, *ResolveIncidentRequest) (*IncidentRow, error)
	UnresolveIncident(context.Context, *UnresolveIncidentRequest) (*IncidentRow, error)
	DismissIncident(context.Context, *DismissIncidentRequest) (*IncidentRow, error)
	UndismissIncident(context.Context, *UndismissIncidentRequest) (*IncidentRow, error)
	SetIncidentNote(context.Context, *SetIncidentNoteRequest) (*IncidentRow, error)
	DeleteIncident(context.Context, *DeleteIncidentRequest) (*DeleteIncidentResponse, error)
	AddCluster(context.Context, *AddClusterRequest) (*Cluster, error)
	RenameCluster(context.Context, *RenameClusterRequest) (*Cluster, error)
	SetClusterGrafana(context.Context, *SetClusterGrafanaRequest) (*Cluster, error)
	DeleteCluster(context.Context, *DeleteClusterRequest) (*DeleteClusterResponse, error)
	AddWatchedNamespace(context.Context, *AddWatchedNamespaceRequest) (*Cluster, error)
	RemoveWatchedNamespace(context.Context, *RemoveWatchedNamespaceRequest) (*Cluster, error)
}

// RegisterIdiosServiceServer registers the HTTP handlers for service IdiosService to the given mux.
func RegisterIdiosServiceServer(server IdiosServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getIdiosServiceHeaders()

	methodHeaders := getListClustersHeaders()
	listClustersHandler := BindingMiddleware[ListClustersRequest](
		genericHandler(server.ListClusters, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		listClustersPathParams, listClustersQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/clusters", listClustersHandler)

	methodHeaders = getListKubeContextsHeaders()
	listKubeContextsHandler := BindingMiddleware[ListKubeContextsRequest](
		genericHandler(server.ListKubeContexts, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		listKubeContextsPathParams, listKubeContextsQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/kube/contexts", listKubeContextsHandler)

	methodHeaders = getListKubeNamespacesHeaders()
	listKubeNamespacesHandler := BindingMiddleware[ListKubeNamespacesRequest](
		genericHandler(server.ListKubeNamespaces, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		listKubeNamespacesPathParams, listKubeNamespacesQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/kube/contexts/{context}/namespaces", listKubeNamespacesHandler)

	methodHeaders = getListIncidentsHeaders()
	listIncidentsHandler := BindingMiddleware[ListIncidentsRequest](
		genericHandler(server.ListIncidents, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		listIncidentsPathParams, listIncidentsQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/incidents", listIncidentsHandler)

	methodHeaders = getGetIncidentCountsHeaders()
	getIncidentCountsHandler := BindingMiddleware[GetIncidentCountsRequest](
		genericHandler(server.GetIncidentCounts, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getIncidentCountsPathParams, getIncidentCountsQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/incidents/counts", getIncidentCountsHandler)

	methodHeaders = getGetIncidentHeaders()
	getIncidentHandler := BindingMiddleware[GetIncidentRequest](
		genericHandler(server.GetIncident, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getIncidentPathParams, getIncidentQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/incidents/{id}", getIncidentHandler)

	methodHeaders = getIncidentTimelineHeaders()
	incidentTimelineHandler := BindingMiddleware[IncidentTimelineRequest](
		genericHandler(server.IncidentTimeline, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		incidentTimelinePathParams, incidentTimelineQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/incidents/{id}/timeline", incidentTimelineHandler)

	methodHeaders = getStreamIncidentsHeaders()
	streamIncidentsHandler := SSEHandler[StreamIncidentsRequest](
		server.StreamIncidents, config.errorHandler, serviceHeaders, methodHeaders,
		streamIncidentsPathParams, streamIncidentsQueryParams,
		"GET", config.marshalOpts,
	)

	config.mux.Handle("GET /v1/incidents/stream", streamIncidentsHandler)

	methodHeaders = getStreamClustersHeaders()
	streamClustersHandler := SSEHandler[StreamClustersRequest](
		server.StreamClusters, config.errorHandler, serviceHeaders, methodHeaders,
		streamClustersPathParams, streamClustersQueryParams,
		"GET", config.marshalOpts,
	)

	config.mux.Handle("GET /v1/clusters/stream", streamClustersHandler)

	methodHeaders = getListPodsHeaders()
	listPodsHandler := BindingMiddleware[ListPodsRequest](
		genericHandler(server.ListPods, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		listPodsPathParams, listPodsQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/pods", listPodsHandler)

	methodHeaders = getGetPodHeaders()
	getPodHandler := BindingMiddleware[GetPodRequest](
		genericHandler(server.GetPod, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getPodPathParams, getPodQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/pods/{uid}", getPodHandler)

	methodHeaders = getPodEventsHeaders()
	podEventsHandler := BindingMiddleware[PodEventsRequest](
		genericHandler(server.PodEvents, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		podEventsPathParams, podEventsQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/pods/{uid}/events", podEventsHandler)

	methodHeaders = getPodHistoryHeaders()
	podHistoryHandler := BindingMiddleware[PodHistoryRequest](
		genericHandler(server.PodHistory, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		podHistoryPathParams, podHistoryQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/pods/{uid}/history", podHistoryHandler)

	methodHeaders = getGetArtifactHeaders()
	getArtifactHandler := BindingMiddleware[GetArtifactRequest](
		genericHandler(server.GetArtifact, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getArtifactPathParams, getArtifactQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/artifacts/{id}", getArtifactHandler)

	methodHeaders = getListWorkloadsHeaders()
	listWorkloadsHandler := BindingMiddleware[ListWorkloadsRequest](
		genericHandler(server.ListWorkloads, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		listWorkloadsPathParams, listWorkloadsQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/workloads", listWorkloadsHandler)

	methodHeaders = getGetWorkloadHeaders()
	getWorkloadHandler := BindingMiddleware[GetWorkloadRequest](
		genericHandler(server.GetWorkload, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getWorkloadPathParams, getWorkloadQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/workloads/{cluster_id}/{namespace}/{kind}/{name}", getWorkloadHandler)

	methodHeaders = getListJobsHeaders()
	listJobsHandler := BindingMiddleware[ListJobsRequest](
		genericHandler(server.ListJobs, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		listJobsPathParams, listJobsQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/jobs", listJobsHandler)

	methodHeaders = getGetStatusHeaders()
	getStatusHandler := BindingMiddleware[GetStatusRequest](
		genericHandler(server.GetStatus, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getStatusPathParams, getStatusQueryParams,
		"GET", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("GET /v1/status", getStatusHandler)

	methodHeaders = getAcknowledgeIncidentHeaders()
	acknowledgeIncidentHandler := BindingMiddleware[AcknowledgeIncidentRequest](
		genericHandler(server.AcknowledgeIncident, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		acknowledgeIncidentPathParams, acknowledgeIncidentQueryParams,
		"POST", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /v1/incidents/{id}/acknowledge", acknowledgeIncidentHandler)

	methodHeaders = getUnacknowledgeIncidentHeaders()
	unacknowledgeIncidentHandler := BindingMiddleware[UnacknowledgeIncidentRequest](
		genericHandler(server.UnacknowledgeIncident, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		unacknowledgeIncidentPathParams, unacknowledgeIncidentQueryParams,
		"DELETE", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("DELETE /v1/incidents/{id}/acknowledge", unacknowledgeIncidentHandler)

	methodHeaders = getResolveIncidentHeaders()
	resolveIncidentHandler := BindingMiddleware[ResolveIncidentRequest](
		genericHandler(server.ResolveIncident, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		resolveIncidentPathParams, resolveIncidentQueryParams,
		"POST", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /v1/incidents/{id}/resolve", resolveIncidentHandler)

	methodHeaders = getUnresolveIncidentHeaders()
	unresolveIncidentHandler := BindingMiddleware[UnresolveIncidentRequest](
		genericHandler(server.UnresolveIncident, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		unresolveIncidentPathParams, unresolveIncidentQueryParams,
		"DELETE", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("DELETE /v1/incidents/{id}/resolve", unresolveIncidentHandler)

	methodHeaders = getDismissIncidentHeaders()
	dismissIncidentHandler := BindingMiddleware[DismissIncidentRequest](
		genericHandler(server.DismissIncident, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		dismissIncidentPathParams, dismissIncidentQueryParams,
		"POST", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /v1/incidents/{id}/dismiss", dismissIncidentHandler)

	methodHeaders = getUndismissIncidentHeaders()
	undismissIncidentHandler := BindingMiddleware[UndismissIncidentRequest](
		genericHandler(server.UndismissIncident, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		undismissIncidentPathParams, undismissIncidentQueryParams,
		"DELETE", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("DELETE /v1/incidents/{id}/dismiss", undismissIncidentHandler)

	methodHeaders = getSetIncidentNoteHeaders()
	setIncidentNoteHandler := BindingMiddleware[SetIncidentNoteRequest](
		genericHandler(server.SetIncidentNote, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		setIncidentNotePathParams, setIncidentNoteQueryParams,
		"PUT", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("PUT /v1/incidents/{id}/note", setIncidentNoteHandler)

	methodHeaders = getDeleteIncidentHeaders()
	deleteIncidentHandler := BindingMiddleware[DeleteIncidentRequest](
		genericHandler(server.DeleteIncident, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		deleteIncidentPathParams, deleteIncidentQueryParams,
		"DELETE", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("DELETE /v1/incidents/{id}", deleteIncidentHandler)

	methodHeaders = getAddClusterHeaders()
	addClusterHandler := BindingMiddleware[AddClusterRequest](
		genericHandler(server.AddCluster, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		addClusterPathParams, addClusterQueryParams,
		"POST", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /v1/clusters", addClusterHandler)

	methodHeaders = getRenameClusterHeaders()
	renameClusterHandler := BindingMiddleware[RenameClusterRequest](
		genericHandler(server.RenameCluster, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		renameClusterPathParams, renameClusterQueryParams,
		"PATCH", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("PATCH /v1/clusters/{id}", renameClusterHandler)

	methodHeaders = getSetClusterGrafanaHeaders()
	setClusterGrafanaHandler := BindingMiddleware[SetClusterGrafanaRequest](
		genericHandler(server.SetClusterGrafana, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		setClusterGrafanaPathParams, setClusterGrafanaQueryParams,
		"PATCH", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("PATCH /v1/clusters/{id}/grafana", setClusterGrafanaHandler)

	methodHeaders = getDeleteClusterHeaders()
	deleteClusterHandler := BindingMiddleware[DeleteClusterRequest](
		genericHandler(server.DeleteCluster, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		deleteClusterPathParams, deleteClusterQueryParams,
		"DELETE", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("DELETE /v1/clusters/{id}", deleteClusterHandler)

	methodHeaders = getAddWatchedNamespaceHeaders()
	addWatchedNamespaceHandler := BindingMiddleware[AddWatchedNamespaceRequest](
		genericHandler(server.AddWatchedNamespace, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		addWatchedNamespacePathParams, addWatchedNamespaceQueryParams,
		"POST", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /v1/clusters/{id}/namespaces", addWatchedNamespaceHandler)

	methodHeaders = getRemoveWatchedNamespaceHeaders()
	removeWatchedNamespaceHandler := BindingMiddleware[RemoveWatchedNamespaceRequest](
		genericHandler(server.RemoveWatchedNamespace, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		removeWatchedNamespacePathParams, removeWatchedNamespaceQueryParams,
		"DELETE", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("DELETE /v1/clusters/{id}/namespaces/{name}", removeWatchedNamespaceHandler)

	return nil
}

// getIdiosServiceHeaders returns the service-level required headers for IdiosService
func getIdiosServiceHeaders() []*sebufhttp.Header {
	return nil
}

// getListClustersHeaders returns the method-level required headers for ListClusters
func getListClustersHeaders() []*sebufhttp.Header {
	return nil
}

// getListKubeContextsHeaders returns the method-level required headers for ListKubeContexts
func getListKubeContextsHeaders() []*sebufhttp.Header {
	return nil
}

// getListKubeNamespacesHeaders returns the method-level required headers for ListKubeNamespaces
func getListKubeNamespacesHeaders() []*sebufhttp.Header {
	return nil
}

// getListIncidentsHeaders returns the method-level required headers for ListIncidents
func getListIncidentsHeaders() []*sebufhttp.Header {
	return nil
}

// getGetIncidentCountsHeaders returns the method-level required headers for GetIncidentCounts
func getGetIncidentCountsHeaders() []*sebufhttp.Header {
	return nil
}

// getGetIncidentHeaders returns the method-level required headers for GetIncident
func getGetIncidentHeaders() []*sebufhttp.Header {
	return nil
}

// getIncidentTimelineHeaders returns the method-level required headers for IncidentTimeline
func getIncidentTimelineHeaders() []*sebufhttp.Header {
	return nil
}

// getStreamIncidentsHeaders returns the method-level required headers for StreamIncidents
func getStreamIncidentsHeaders() []*sebufhttp.Header {
	return nil
}

// getStreamClustersHeaders returns the method-level required headers for StreamClusters
func getStreamClustersHeaders() []*sebufhttp.Header {
	return nil
}

// getListPodsHeaders returns the method-level required headers for ListPods
func getListPodsHeaders() []*sebufhttp.Header {
	return nil
}

// getGetPodHeaders returns the method-level required headers for GetPod
func getGetPodHeaders() []*sebufhttp.Header {
	return nil
}

// getPodEventsHeaders returns the method-level required headers for PodEvents
func getPodEventsHeaders() []*sebufhttp.Header {
	return nil
}

// getPodHistoryHeaders returns the method-level required headers for PodHistory
func getPodHistoryHeaders() []*sebufhttp.Header {
	return nil
}

// getGetArtifactHeaders returns the method-level required headers for GetArtifact
func getGetArtifactHeaders() []*sebufhttp.Header {
	return nil
}

// getListWorkloadsHeaders returns the method-level required headers for ListWorkloads
func getListWorkloadsHeaders() []*sebufhttp.Header {
	return nil
}

// getGetWorkloadHeaders returns the method-level required headers for GetWorkload
func getGetWorkloadHeaders() []*sebufhttp.Header {
	return nil
}

// getListJobsHeaders returns the method-level required headers for ListJobs
func getListJobsHeaders() []*sebufhttp.Header {
	return nil
}

// getGetStatusHeaders returns the method-level required headers for GetStatus
func getGetStatusHeaders() []*sebufhttp.Header {
	return nil
}

// getAcknowledgeIncidentHeaders returns the method-level required headers for AcknowledgeIncident
func getAcknowledgeIncidentHeaders() []*sebufhttp.Header {
	return nil
}

// getUnacknowledgeIncidentHeaders returns the method-level required headers for UnacknowledgeIncident
func getUnacknowledgeIncidentHeaders() []*sebufhttp.Header {
	return nil
}

// getResolveIncidentHeaders returns the method-level required headers for ResolveIncident
func getResolveIncidentHeaders() []*sebufhttp.Header {
	return nil
}

// getUnresolveIncidentHeaders returns the method-level required headers for UnresolveIncident
func getUnresolveIncidentHeaders() []*sebufhttp.Header {
	return nil
}

// getDismissIncidentHeaders returns the method-level required headers for DismissIncident
func getDismissIncidentHeaders() []*sebufhttp.Header {
	return nil
}

// getUndismissIncidentHeaders returns the method-level required headers for UndismissIncident
func getUndismissIncidentHeaders() []*sebufhttp.Header {
	return nil
}

// getSetIncidentNoteHeaders returns the method-level required headers for SetIncidentNote
func getSetIncidentNoteHeaders() []*sebufhttp.Header {
	return nil
}

// getDeleteIncidentHeaders returns the method-level required headers for DeleteIncident
func getDeleteIncidentHeaders() []*sebufhttp.Header {
	return nil
}

// getAddClusterHeaders returns the method-level required headers for AddCluster
func getAddClusterHeaders() []*sebufhttp.Header {
	return nil
}

// getRenameClusterHeaders returns the method-level required headers for RenameCluster
func getRenameClusterHeaders() []*sebufhttp.Header {
	return nil
}

// getSetClusterGrafanaHeaders returns the method-level required headers for SetClusterGrafana
func getSetClusterGrafanaHeaders() []*sebufhttp.Header {
	return nil
}

// getDeleteClusterHeaders returns the method-level required headers for DeleteCluster
func getDeleteClusterHeaders() []*sebufhttp.Header {
	return nil
}

// getAddWatchedNamespaceHeaders returns the method-level required headers for AddWatchedNamespace
func getAddWatchedNamespaceHeaders() []*sebufhttp.Header {
	return nil
}

// getRemoveWatchedNamespaceHeaders returns the method-level required headers for RemoveWatchedNamespace
func getRemoveWatchedNamespaceHeaders() []*sebufhttp.Header {
	return nil
}

// listClustersPathParams contains path parameter configuration for ListClusters
var listClustersPathParams = []PathParamConfig{}

// listClustersQueryParams contains query parameter configuration for ListClusters
var listClustersQueryParams = []QueryParamConfig{
	{QueryName: "cluster_ids", FieldName: "cluster_ids", Required: false},
}

// listKubeContextsPathParams contains path parameter configuration for ListKubeContexts
var listKubeContextsPathParams = []PathParamConfig{}

// listKubeContextsQueryParams contains query parameter configuration for ListKubeContexts
var listKubeContextsQueryParams = []QueryParamConfig{}

// listKubeNamespacesPathParams contains path parameter configuration for ListKubeNamespaces
var listKubeNamespacesPathParams = []PathParamConfig{
	{URLParam: "context", FieldName: "context"},
}

// listKubeNamespacesQueryParams contains query parameter configuration for ListKubeNamespaces
var listKubeNamespacesQueryParams = []QueryParamConfig{}

// listIncidentsPathParams contains path parameter configuration for ListIncidents
var listIncidentsPathParams = []PathParamConfig{}

// listIncidentsQueryParams contains query parameter configuration for ListIncidents
var listIncidentsQueryParams = []QueryParamConfig{
	{QueryName: "cluster_ids", FieldName: "cluster_ids", Required: false},
	{QueryName: "state", FieldName: "state", Required: false},
	{QueryName: "category", FieldName: "category", Required: false},
	{QueryName: "namespace", FieldName: "namespace", Required: false},
	{QueryName: "workload_kind", FieldName: "workload_kind", Required: false},
	{QueryName: "workload_name", FieldName: "workload_name", Required: false},
	{QueryName: "pod_uid", FieldName: "pod_uid", Required: false},
	{QueryName: "job_uid", FieldName: "job_uid", Required: false},
	{QueryName: "limit", FieldName: "limit", Required: false},
	{QueryName: "node_name", FieldName: "node_name", Required: false},
	{QueryName: "pod_name", FieldName: "pod_name", Required: false},
}

// getIncidentCountsPathParams contains path parameter configuration for GetIncidentCounts
var getIncidentCountsPathParams = []PathParamConfig{}

// getIncidentCountsQueryParams contains query parameter configuration for GetIncidentCounts
var getIncidentCountsQueryParams = []QueryParamConfig{
	{QueryName: "cluster_ids", FieldName: "cluster_ids", Required: false},
	{QueryName: "state", FieldName: "state", Required: false},
	{QueryName: "category", FieldName: "category", Required: false},
}

// getIncidentPathParams contains path parameter configuration for GetIncident
var getIncidentPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// getIncidentQueryParams contains query parameter configuration for GetIncident
var getIncidentQueryParams = []QueryParamConfig{}

// incidentTimelinePathParams contains path parameter configuration for IncidentTimeline
var incidentTimelinePathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// incidentTimelineQueryParams contains query parameter configuration for IncidentTimeline
var incidentTimelineQueryParams = []QueryParamConfig{}

// streamIncidentsPathParams contains path parameter configuration for StreamIncidents
var streamIncidentsPathParams = []PathParamConfig{}

// streamIncidentsQueryParams contains query parameter configuration for StreamIncidents
var streamIncidentsQueryParams = []QueryParamConfig{
	{QueryName: "cluster_ids", FieldName: "cluster_ids", Required: false},
}

// streamClustersPathParams contains path parameter configuration for StreamClusters
var streamClustersPathParams = []PathParamConfig{}

// streamClustersQueryParams contains query parameter configuration for StreamClusters
var streamClustersQueryParams = []QueryParamConfig{
	{QueryName: "cluster_ids", FieldName: "cluster_ids", Required: false},
}

// listPodsPathParams contains path parameter configuration for ListPods
var listPodsPathParams = []PathParamConfig{}

// listPodsQueryParams contains query parameter configuration for ListPods
var listPodsQueryParams = []QueryParamConfig{
	{QueryName: "cluster_ids", FieldName: "cluster_ids", Required: false},
	{QueryName: "namespace", FieldName: "namespace", Required: false},
	{QueryName: "workload_kind", FieldName: "workload_kind", Required: false},
	{QueryName: "workload_name", FieldName: "workload_name", Required: false},
	{QueryName: "live", FieldName: "live", Required: false},
	{QueryName: "limit", FieldName: "limit", Required: false},
	{QueryName: "pod_name", FieldName: "pod_name", Required: false},
	{QueryName: "job_uid", FieldName: "job_uid", Required: false},
}

// getPodPathParams contains path parameter configuration for GetPod
var getPodPathParams = []PathParamConfig{
	{URLParam: "uid", FieldName: "uid"},
}

// getPodQueryParams contains query parameter configuration for GetPod
var getPodQueryParams = []QueryParamConfig{}

// podEventsPathParams contains path parameter configuration for PodEvents
var podEventsPathParams = []PathParamConfig{
	{URLParam: "uid", FieldName: "uid"},
}

// podEventsQueryParams contains query parameter configuration for PodEvents
var podEventsQueryParams = []QueryParamConfig{
	{QueryName: "limit", FieldName: "limit", Required: false},
}

// podHistoryPathParams contains path parameter configuration for PodHistory
var podHistoryPathParams = []PathParamConfig{
	{URLParam: "uid", FieldName: "uid"},
}

// podHistoryQueryParams contains query parameter configuration for PodHistory
var podHistoryQueryParams = []QueryParamConfig{}

// getArtifactPathParams contains path parameter configuration for GetArtifact
var getArtifactPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// getArtifactQueryParams contains query parameter configuration for GetArtifact
var getArtifactQueryParams = []QueryParamConfig{}

// listWorkloadsPathParams contains path parameter configuration for ListWorkloads
var listWorkloadsPathParams = []PathParamConfig{}

// listWorkloadsQueryParams contains query parameter configuration for ListWorkloads
var listWorkloadsQueryParams = []QueryParamConfig{
	{QueryName: "cluster_ids", FieldName: "cluster_ids", Required: false},
	{QueryName: "namespace", FieldName: "namespace", Required: false},
	{QueryName: "limit", FieldName: "limit", Required: false},
}

// getWorkloadPathParams contains path parameter configuration for GetWorkload
var getWorkloadPathParams = []PathParamConfig{
	{URLParam: "cluster_id", FieldName: "cluster_id"},
	{URLParam: "namespace", FieldName: "namespace"},
	{URLParam: "kind", FieldName: "kind"},
	{URLParam: "name", FieldName: "name"},
}

// getWorkloadQueryParams contains query parameter configuration for GetWorkload
var getWorkloadQueryParams = []QueryParamConfig{
	{QueryName: "pods_live", FieldName: "pods_live", Required: false},
	{QueryName: "pods_limit", FieldName: "pods_limit", Required: false},
}

// listJobsPathParams contains path parameter configuration for ListJobs
var listJobsPathParams = []PathParamConfig{}

// listJobsQueryParams contains query parameter configuration for ListJobs
var listJobsQueryParams = []QueryParamConfig{
	{QueryName: "cluster_ids", FieldName: "cluster_ids", Required: false},
	{QueryName: "namespace", FieldName: "namespace", Required: false},
	{QueryName: "cronjob_uid", FieldName: "cronjob_uid", Required: false},
	{QueryName: "limit", FieldName: "limit", Required: false},
	{QueryName: "cronjob_name", FieldName: "cronjob_name", Required: false},
	{QueryName: "live", FieldName: "live", Required: false},
	{QueryName: "failed", FieldName: "failed", Required: false},
	{QueryName: "job_uid", FieldName: "job_uid", Required: false},
}

// getStatusPathParams contains path parameter configuration for GetStatus
var getStatusPathParams = []PathParamConfig{}

// getStatusQueryParams contains query parameter configuration for GetStatus
var getStatusQueryParams = []QueryParamConfig{}

// acknowledgeIncidentPathParams contains path parameter configuration for AcknowledgeIncident
var acknowledgeIncidentPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// acknowledgeIncidentQueryParams contains query parameter configuration for AcknowledgeIncident
var acknowledgeIncidentQueryParams = []QueryParamConfig{}

// unacknowledgeIncidentPathParams contains path parameter configuration for UnacknowledgeIncident
var unacknowledgeIncidentPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// unacknowledgeIncidentQueryParams contains query parameter configuration for UnacknowledgeIncident
var unacknowledgeIncidentQueryParams = []QueryParamConfig{}

// resolveIncidentPathParams contains path parameter configuration for ResolveIncident
var resolveIncidentPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// resolveIncidentQueryParams contains query parameter configuration for ResolveIncident
var resolveIncidentQueryParams = []QueryParamConfig{}

// unresolveIncidentPathParams contains path parameter configuration for UnresolveIncident
var unresolveIncidentPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// unresolveIncidentQueryParams contains query parameter configuration for UnresolveIncident
var unresolveIncidentQueryParams = []QueryParamConfig{}

// dismissIncidentPathParams contains path parameter configuration for DismissIncident
var dismissIncidentPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// dismissIncidentQueryParams contains query parameter configuration for DismissIncident
var dismissIncidentQueryParams = []QueryParamConfig{}

// undismissIncidentPathParams contains path parameter configuration for UndismissIncident
var undismissIncidentPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// undismissIncidentQueryParams contains query parameter configuration for UndismissIncident
var undismissIncidentQueryParams = []QueryParamConfig{}

// setIncidentNotePathParams contains path parameter configuration for SetIncidentNote
var setIncidentNotePathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// setIncidentNoteQueryParams contains query parameter configuration for SetIncidentNote
var setIncidentNoteQueryParams = []QueryParamConfig{}

// deleteIncidentPathParams contains path parameter configuration for DeleteIncident
var deleteIncidentPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// deleteIncidentQueryParams contains query parameter configuration for DeleteIncident
var deleteIncidentQueryParams = []QueryParamConfig{}

// addClusterPathParams contains path parameter configuration for AddCluster
var addClusterPathParams = []PathParamConfig{}

// addClusterQueryParams contains query parameter configuration for AddCluster
var addClusterQueryParams = []QueryParamConfig{}

// renameClusterPathParams contains path parameter configuration for RenameCluster
var renameClusterPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// renameClusterQueryParams contains query parameter configuration for RenameCluster
var renameClusterQueryParams = []QueryParamConfig{}

// setClusterGrafanaPathParams contains path parameter configuration for SetClusterGrafana
var setClusterGrafanaPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// setClusterGrafanaQueryParams contains query parameter configuration for SetClusterGrafana
var setClusterGrafanaQueryParams = []QueryParamConfig{}

// deleteClusterPathParams contains path parameter configuration for DeleteCluster
var deleteClusterPathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// deleteClusterQueryParams contains query parameter configuration for DeleteCluster
var deleteClusterQueryParams = []QueryParamConfig{}

// addWatchedNamespacePathParams contains path parameter configuration for AddWatchedNamespace
var addWatchedNamespacePathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
}

// addWatchedNamespaceQueryParams contains query parameter configuration for AddWatchedNamespace
var addWatchedNamespaceQueryParams = []QueryParamConfig{}

// removeWatchedNamespacePathParams contains path parameter configuration for RemoveWatchedNamespace
var removeWatchedNamespacePathParams = []PathParamConfig{
	{URLParam: "id", FieldName: "id"},
	{URLParam: "name", FieldName: "name"},
}

// removeWatchedNamespaceQueryParams contains query parameter configuration for RemoveWatchedNamespace
var removeWatchedNamespaceQueryParams = []QueryParamConfig{}
