// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: idios/v1/service.proto

package idiosv1

import (
	"net/http"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// ErrorHandler is called when an error occurs.
//
// You can:
//   - Set headers via w.Header().Set(...)
//   - Set status code via w.WriteHeader(...)
//   - Return a proto.Message to be marshaled as the response body
//   - Return nil to use the default error response (ValidationError or Error)
//
// If you write directly to w (via w.Write()), the response is considered
// complete and no further writing occurs.
//
// Use errors.As() to inspect error types: *sebufhttp.ValidationError or *sebufhttp.Error
type ErrorHandler func(w http.ResponseWriter, r *http.Request, err error) proto.Message

// ServerOption configures a Server
type ServerOption func(c *serverConfiguration)

type serverConfiguration struct {
	mux          *http.ServeMux
	withMux      bool
	errorHandler ErrorHandler
	marshalOpts  protojson.MarshalOptions
}

func getDefaultConfiguration() *serverConfiguration {
	return &serverConfiguration{
		mux:     http.DefaultServeMux,
		withMux: false,
	}
}

func getConfiguration(options ...ServerOption) *serverConfiguration {
	configuration := getDefaultConfiguration()
	for _, option := range options {
		option(configuration)
	}
	return configuration
}

// WithMux configures the Server to use the given ServeMux
func WithMux(mux *http.ServeMux) ServerOption {
	return func(c *serverConfiguration) {
		c.mux = mux
		c.withMux = true
	}
}

// WithErrorHandler configures a custom error handler for the server.
func WithErrorHandler(handler ErrorHandler) ServerOption {
	return func(c *serverConfiguration) {
		c.errorHandler = handler
	}
}

// WithMarshalOptions configures the protojson.MarshalOptions used when serializing
// JSON responses (including SSE events and error bodies). The zero value preserves
// default behavior. Use this to surface zero-value fields with EmitUnpopulated,
// switch to proto field names with UseProtoNames, or tune any other protojson knob.
func WithMarshalOptions(opts protojson.MarshalOptions) ServerOption {
	return func(c *serverConfiguration) {
		c.marshalOpts = opts
	}
}
