// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: idios/v1/status.proto

package idiosv1

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for GapCount.
// This method handles enum_value fields and nested messages: gap
func (x *GapCount) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite gap to custom enum_value strings
	for _, k := range []string{"gap"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := captureGapFromJSON[s]; ok {
			raw[k], _ = json.Marshal(captureGapToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for GapCount.
func (x *GapCount) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for GapCount.
// This method handles enum_value fields and nested messages: gap
func (x *GapCount) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite gap from custom enum_value strings to proto names
	for _, k := range []string{"gap"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := captureGapFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for GapCount.
func (x *GapCount) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for CaptureStats.
// This method handles enum_value fields and nested messages: gaps
func (x *CaptureStats) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "gaps" forwarding opts to each element
	if len(x.Gaps) > 0 {
		items := make([]json.RawMessage, 0, len(x.Gaps))
		for _, item := range x.Gaps {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"gaps"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for CaptureStats.
func (x *CaptureStats) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for CaptureStats.
// This method handles enum_value fields and nested messages: gaps
func (x *CaptureStats) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "gaps" using its custom unmarshaler
	for _, k := range []string{"gaps"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &GapCount{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for CaptureStats.
func (x *CaptureStats) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for CloseReasonCount.
// This method handles enum_value fields and nested messages: close_reason
func (x *CloseReasonCount) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite close_reason to custom enum_value strings
	for _, k := range []string{"closeReason", "close_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := closeReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(closeReasonToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for CloseReasonCount.
func (x *CloseReasonCount) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for CloseReasonCount.
// This method handles enum_value fields and nested messages: close_reason
func (x *CloseReasonCount) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite close_reason from custom enum_value strings to proto names
	for _, k := range []string{"closeReason", "close_reason"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := closeReasonFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for CloseReasonCount.
func (x *CloseReasonCount) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for Status.
// This method handles enum_value fields and nested messages: capture, open_by_category, closed_by_reason
func (x *Status) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize "capture" forwarding opts when child supports MarshalJSONSebuf
	if x.Capture != nil {
		if m, ok := any(x.Capture).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			childData, childErr := m.MarshalJSONSebuf(opts)
			if childErr != nil {
				return nil, childErr
			}
			for _, k := range []string{"capture"} {
				if _, ok := raw[k]; ok {
					raw[k] = childData
				}
			}
		}
	}

	// Re-serialize repeated "openByCategory" forwarding opts to each element
	if len(x.OpenByCategory) > 0 {
		items := make([]json.RawMessage, 0, len(x.OpenByCategory))
		for _, item := range x.OpenByCategory {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"openByCategory", "open_by_category"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	// Re-serialize repeated "closedByReason" forwarding opts to each element
	if len(x.ClosedByReason) > 0 {
		items := make([]json.RawMessage, 0, len(x.ClosedByReason))
		for _, item := range x.ClosedByReason {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"closedByReason", "closed_by_reason"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for Status.
func (x *Status) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for Status.
// This method handles enum_value fields and nested messages: capture, open_by_category, closed_by_reason
func (x *Status) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "capture" using its custom unmarshaler
	for _, k := range []string{"capture"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		inner := &CaptureStats{}
		if u, ok := any(inner).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(rawVal, opts); err != nil {
				return err
			}
		} else if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, marshalErr := protojson.Marshal(inner)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = innerJSON
	}

	// Handle "openByCategory" using its custom unmarshaler
	for _, k := range []string{"openByCategory", "open_by_category"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &CategoryCount{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Handle "closedByReason" using its custom unmarshaler
	for _, k := range []string{"closedByReason", "closed_by_reason"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &CloseReasonCount{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for Status.
func (x *Status) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
