// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: idios/v1/workloads.proto

package idiosv1

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for WorkloadRow.
// This method handles enum_value fields and nested messages: incidents_by_category
func (x *WorkloadRow) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "incidentsByCategory" forwarding opts to each element
	if len(x.IncidentsByCategory) > 0 {
		items := make([]json.RawMessage, 0, len(x.IncidentsByCategory))
		for _, item := range x.IncidentsByCategory {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"incidentsByCategory", "incidents_by_category"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for WorkloadRow.
func (x *WorkloadRow) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for WorkloadRow.
// This method handles enum_value fields and nested messages: incidents_by_category
func (x *WorkloadRow) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "incidentsByCategory" using its custom unmarshaler
	for _, k := range []string{"incidentsByCategory", "incidents_by_category"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &CategoryCount{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for WorkloadRow.
func (x *WorkloadRow) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for WorkloadsResponse.
// This method handles enum_value fields and nested messages: workloads
func (x *WorkloadsResponse) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize repeated "workloads" forwarding opts to each element
	if len(x.Workloads) > 0 {
		items := make([]json.RawMessage, 0, len(x.Workloads))
		for _, item := range x.Workloads {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"workloads"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for WorkloadsResponse.
func (x *WorkloadsResponse) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for WorkloadsResponse.
// This method handles enum_value fields and nested messages: workloads
func (x *WorkloadsResponse) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "workloads" using its custom unmarshaler
	for _, k := range []string{"workloads"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &WorkloadRow{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for WorkloadsResponse.
func (x *WorkloadsResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for WorkloadDetail.
// This method handles enum_value fields and nested messages: workload, pods
func (x *WorkloadDetail) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Re-serialize "workload" forwarding opts when child supports MarshalJSONSebuf
	if x.Workload != nil {
		if m, ok := any(x.Workload).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			childData, childErr := m.MarshalJSONSebuf(opts)
			if childErr != nil {
				return nil, childErr
			}
			for _, k := range []string{"workload"} {
				if _, ok := raw[k]; ok {
					raw[k] = childData
				}
			}
		}
	}

	// Re-serialize repeated "pods" forwarding opts to each element
	if len(x.Pods) > 0 {
		items := make([]json.RawMessage, 0, len(x.Pods))
		for _, item := range x.Pods {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"pods"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for WorkloadDetail.
func (x *WorkloadDetail) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for WorkloadDetail.
// This method handles enum_value fields and nested messages: workload, pods
func (x *WorkloadDetail) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle "workload" using its custom unmarshaler
	for _, k := range []string{"workload"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		inner := &WorkloadRow{}
		if u, ok := any(inner).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(rawVal, opts); err != nil {
				return err
			}
		} else if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, marshalErr := protojson.Marshal(inner)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = innerJSON
	}

	// Handle "pods" using its custom unmarshaler
	for _, k := range []string{"pods"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &PodRow{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for WorkloadDetail.
func (x *WorkloadDetail) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
