import AppKit
import IdiosModel
import SwiftUI
import UniformTypeIdentifiers

/// AskAIAction is what a person chose to do with the prompt: put it on the
/// clipboard, or write it where they say.
enum AskAIAction: Hashable {
    case copy
    case save

    /// verb is the button that carries the action out.
    var verb: String {
        switch self {
        case .copy: "Copy"
        case .save: "Save..."
        }
    }
}

/// AskAIRequest is one menu item: which prompt, and what to do with it.
struct AskAIRequest: Identifiable, Hashable {
    let mode: PromptMode
    let action: AskAIAction

    var id: String { "\(mode.rawValue)-\(action.verb)" }
}

/// AskAISheet fetches the prompt the daemon renders, says how large it is, and
/// carries the action out only once a person has seen the size.
struct AskAISheet: View {
    let id: String
    let request: AskAIRequest

    @Environment(DaemonConnection.self) private var connection
    @Environment(\.dismiss) private var dismiss
    @State private var store = PromptStore()

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text(request.mode.title).font(.system(size: 13, weight: .semibold))
            explainer
            Divider()
            state
            HStack {
                Spacer()
                Button("Cancel") { dismiss() }
                    .keyboardShortcut(.cancelAction)
                Button(request.action.verb) { carryOut() }
                    .keyboardShortcut(.defaultAction)
                    .disabled(store.text == nil)
            }
        }
        .padding(20)
        .frame(width: 460)
        .task(id: connection.generation) {
            await store.load(id: id, mode: request.mode, connection: connection)
        }
    }

    // The MCP prompt is worth nothing to an agent that cannot reach the server
    // it names, so the sheet says what the option requires before it is used.
    @ViewBuilder private var explainer: some View {
        switch request.mode {
        case .mcp:
            Text(
                "The agent reads the evidence itself over the idios MCP server, which is "
                    + "read-only and runs on this machine. Add it to the agent's MCP "
                    + "configuration:")
                .font(.system(size: 11.5))
                .foregroundStyle(.secondary)
                .lineLimit(nil)
            HStack(spacing: 8) {
                Text(serverConfig)
                    .font(.system(size: 11.5, design: .monospaced))
                    .textSelection(.enabled)
                    .lineLimit(nil)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 5)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(RoundedRectangle(cornerRadius: 6).fill(.quaternary.opacity(0.25)))
                Button("Copy") { copyToClipboard(serverConfig) }
            }
        case .snapshot:
            Text(
                "The whole recorded evidence travels with the prompt: the detail and the "
                    + "timeline, the pod, its events, every captured log, the pod object with "
                    + "its environment values stripped, and the related incidents. No MCP "
                    + "server is needed.")
                .font(.system(size: 11.5))
                .foregroundStyle(.secondary)
                .lineLimit(nil)
        }
    }

    @ViewBuilder private var state: some View {
        if let size = store.size {
            Text("\(size) of text, generated by the daemon.")
                .font(.system(size: 11.5))
                .foregroundStyle(.secondary)
        } else if let error = store.error {
            WrapText(value: error.message)
                .font(.system(size: 11.5))
                .foregroundStyle(BadgeStyle.red.text)
        } else {
            HStack(spacing: 8) {
                ProgressView().controlSize(.small)
                Text("Generating...").font(.system(size: 11.5)).foregroundStyle(.secondary)
            }
        }
    }

    // The entry must name the command as it resolves on this machine: the
    // installed app's bundled binary is not on PATH.
    private var serverConfig: String {
        mcpServerConfig(command: DaemonManager.mcpCommand)
    }

    private func carryOut() {
        guard let text = store.text else { return }
        switch request.action {
        case .copy:
            copyToClipboard(text)
        case .save:
            save(text)
        }
        dismiss()
    }

    private func copyToClipboard(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    // A save panel the person cancels leaves the prompt where it was; there is
    // nothing to report and nothing to undo.
    private func save(_ text: String) {
        let panel = NSSavePanel()
        panel.nameFieldStringValue = request.mode.fileName(incident: id)
        panel.allowedContentTypes = [.plainText]
        guard panel.runModal() == .OK, let url = panel.url else { return }
        try? text.write(to: url, atomically: true, encoding: .utf8)
    }
}
